In [2]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [3]:
jd='''Role - Senior Big Data Engineer
Required Technical skills - Big Data, Python, Spark, Data brick, data Spark
Desired Experience Range - 5 + years
Location of Requirement - PAN India
Desired Competencies
Must-Have
Good hands on experience in Python programming
· Data Engineering experience using AWS core services (Lambda, Glue, EMR and RedShift)
· Required skill set- SQL, Airflow · Must – Have Experience with snowflake

· Responsibility – Will be accountable for build/test complex data pipelines (batch and near real time) · Expectation – Readable documentation of all the components being develop · Experience in writing SQLs and stored procedures · Working experience with RDBMS (Oracle / Teradata)
Good-to-Have
· Good understanding of Data warehouse
· Familiarize in ETL tools like Informatica
· Experience working with NoSQL database like DynamoDB or MongoDB .'''

In [4]:


def remove_stuff(jd):
    jd_clean = jd.replace("\xa0", "").replace("/", "").replace(".", ". ").replace("●", "")
    return jd_clean

In [5]:
def get_cv(): #cleaned, processed, nlped cv content
    url='cv.csv'
    return pd.read_csv(url) 
# db_expander = st.beta_expander(label='Submitted resume:')
# with db_expander:
df = get_cv()

# checking data

In [6]:
# cv data

In [7]:
df

Unnamed: 0                 name                         email  \
0            0       Sukanya Jangra    Jangrasukanya066@gmail.com   
1            1          Abhay Kumar       abhayownsthis@gmail.com   
2            2    Abhijit Manepatil                           NaN   
3            3     Abhinav Abhishek           abhi4navv@gmail.com   
4            4       Aniket Kashyap         monu.aniket@gmail.com   
5            5        Anirudh Anand      anirudhanand80@gmail.com   
6            6         ASHRAY RAINA       ashrayraina22@gmail.com   
7            7    Ramachandran Iyer          Ganesh2480@gmail.com   
8            8       Himanshu Tyagi                           NaN   
9            9           Jalpa Dave                           NaN   
10          10   Kishore Ramiyengar        kishor.priya@gmail.com   
11          11    Mohnish Chaudhary                           NaN   
12          12        Pawan Kumar A           pawan9964@gmail.com   
13          13      Prikshit Sharma  prikshitsharma8024@gmail.com   
14          14  Priyanka Srivastava    priyankasrvstv16@gmail.com   
15          15     Rakshit Khajuria    rakshitraina1234@gmail.com   
16          16     Rakshit Khajuria    rakshitraina1234@gmail.com   
17          17                  S W       swayamgupta74@gmail.com   

   mobile_number                                             skills  \
0            NaN  ['Data entry', 'Microsoft excel', 'Word', 'Htm...   
1        9978045  ['Technical', 'R', 'Analytical', 'Keras', 'Ui'...   
2            NaN  ['Marketing', 'R', 'Mining', 'Email', 'Keras',...   
3     8757656959  ['Electronics', 'Spyder', 'Sales', 'Mining', '...   
4     9691316944  ['Technical', 'Spyder', 'Mining', 'Keras', 'Em...   
5     8082366408  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...   
6     7780995937  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...   
7     9820463399  ['Technical', 'Crm', 'Itil', 'Sales', 'Project...   
8     0800189689  ['Electronics', 'Sales', 'Analytical', 'Email'...   
9            NaN  ['Technical', 'Analyze', 'Marketing', 'R', 'Em...   
10      007-2008  ['Technical', 'Analyze', 'Sales', 'Finance', '...   
11           NaN  ['Technical', 'Gensim', 'Email', 'Mining', 'He...   
12    8008636324  ['Technical', 'R', 'Analytical', 'Keras', 'Sec...   
13    7780992150  ['Electronics', 'Analytical', 'Sql', 'Programm...   
14    8948669980  ['Pandas', 'Analytics', 'System', 'Python', 'J...   
15    9149556155  ['Electronics', 'Seaborn', 'Tensorflow', 'Metr...   
16    9149556155  ['Electronics', 'Analyze', 'Textblob', 'Coding...   
17    9797402957  ['Keras', 'Sql', 'Database', 'Programming', 'L...   

                                               degree  no_of_pages  \
0                                                None            1   
1   ['e-commerce', 'Bachelor of Engineering,Comput...            4   
2   ['Master of Engineering', 'Master in Computer ...            3   
3                                                None            3   
4   ['Bachelor of Engineering, Computer Science  n...            3   
5                                                None            2   
6                                          ['B.tech']            1   
7                           ['Bachelors of Commerce']            2   
8                            ['BTech in Electronics']            2   
9                      ['B.E. in Computer', 'M.Tech']            3   
10                 ['Bachelor of Technology (Civil)']            9   
11                   ['BE in Information Technology']            3   
12  ['Bachelor of Science (Btech) in Computer Scie...            2   
13      ['B Tech, Shri Mata Vaishno Devi University']            2   
14  ['PG certication in Data Science & MLnAcadgild...            1   
15  ['Electronics and Communication nEngineering S...            1   
16  ['Electronics and Communication, Engineering S...            2   
17                        ['Bachelors of Technology']            1   

           

In [8]:
df["All"]

0     Sukanya JangraBhiwani, HaryanaJangrasukanya066...
1     Abhay KumarLead Data Scientist - Computer Visi...
2     Abhijit ManepatilData Scientist with Master in...
3     Abhinav AbhishekSenior Software Developer/Data...
4     Aniket KashyapSoftware Developer/Data Scientis...
5     Anirudh AnandMachine Learning Engineeranirudha...
6     ASHRAY RAINAashrayraina22@gmail.com 7780995937...
7     Ramachandran IyerIIM Ahmedabad Alumnus| SMP | ...
8     Himanshu TyagiPune, Maharashtra - Email me on ...
9     Jalpa DaveData Scientist - Elegant Microweb Te...
10    Kishore Ramiyengar LakshmipprasannaC 404, Gaan...
11    Mohnish ChaudharyDECISION SCIENTIST - MU SIGMA...
12    Pawan Kumar Apawan9964@gmail.com#45, 8th cross...
13    Prikshit SharmaJammu,India prikshitsharma8024@...
14    Priyanka SrivastavaData ScientistData Science ...
15    Rakshit KhajuriaMachine Learning EngineerA 2+ ...
16    Rakshit KhajuriaMachine Learning EngineerTalab...
17    S W A Y A M G U P T A Jammu DOB: 9-Jan-200

In [9]:
# job discription entered by recuriter

In [10]:
jd

'Role - Senior Big Data Engineer\nRequired Technical skills - Big Data, Python, Spark, Data brick, data Spark\nDesired Experience Range - 5 + years\nLocation of Requirement - PAN India\nDesired Competencies\nMust-Have\nGood hands on experience in Python programming\n· Data Engineering experience using AWS core services (Lambda, Glue, EMR and RedShift)\n· Required skill set- SQL, Airflow · Must – Have Experience with snowflake\n\n· Responsibility – Will be accountable for build/test complex data pipelines (batch and near real time) · Expectation – Readable documentation of all the components being develop · Experience in writing SQLs and stored procedures · Working experience with RDBMS (Oracle / Teradata)\nGood-to-Have\n· Good understanding of Data warehouse\n· Familiarize in ETL tools like Informatica\n· Experience working with NoSQL database like DynamoDB or MongoDB .'

In [11]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’'))
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    clean_text = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return clean_text

In [12]:
NLP_Processed_JD=nlp(jd)


In [13]:
NLP_Processed_JD

['role',
 'senior',
 'big',
 'data',
 'engineerrequired',
 'technical',
 'skill',
 'big',
 'data',
 'python',
 'spark',
 'data',
 'brick',
 'data',
 'sparkdesired',
 'experience',
 'range',
 '5',
 'yearslocation',
 'requirement',
 'pan',
 'indiadesired',
 'competenciesmust-havegood',
 'hand',
 'experience',
 'python',
 'programming·',
 'data',
 'engineering',
 'experience',
 'using',
 'aws',
 'core',
 'service',
 'lambda',
 'glue',
 'emr',
 'redshift',
 '·',
 'required',
 'skill',
 'set-',
 'sql',
 'airflow',
 '·',
 'must',
 'experience',
 'snowflake·',
 'responsibility',
 'accountable',
 'build/test',
 'complex',
 'data',
 'pipeline',
 'batch',
 'near',
 'real',
 'time',
 '·',
 'expectation',
 'readable',
 'documentation',
 'component',
 'develop',
 '·',
 'experience',
 'writing',
 'sqls',
 'stored',
 'procedure',
 '·',
 'working',
 'experience',
 'rdbms',
 'oracle',
 'teradata',
 'good-to-have·',
 'good',
 'understanding',
 'data',
 'warehouse·',
 'familiarize',
 'etl',
 'tool',
 'li

In [14]:
################################################################################################################################

In [15]:
jd_df=pd.DataFrame()
# jd_df['hi']=['I']
jd_df['jd']=[' '.join(NLP_Processed_JD)]

In [16]:
jd_df['jd'].values[0]

'role senior big data engineerrequired technical skill big data python spark data brick data sparkdesired experience range 5 yearslocation requirement pan indiadesired competenciesmust-havegood hand experience python programming· data engineering experience using aws core service lambda glue emr redshift · required skill set- sql airflow · must experience snowflake· responsibility accountable build/test complex data pipeline batch near real time · expectation readable documentation component develop · experience writing sqls stored procedure · working experience rdbms oracle teradata good-to-have· good understanding data warehouse· familiarize etl tool like informatica· experience working nosql database like dynamodb mongodb'

In [17]:
clean_jd=jd_df['jd'].values[0]

In [18]:
##############################################################################################################################

In [19]:
df["All"]

0     Sukanya JangraBhiwani, HaryanaJangrasukanya066...
1     Abhay KumarLead Data Scientist - Computer Visi...
2     Abhijit ManepatilData Scientist with Master in...
3     Abhinav AbhishekSenior Software Developer/Data...
4     Aniket KashyapSoftware Developer/Data Scientis...
5     Anirudh AnandMachine Learning Engineeranirudha...
6     ASHRAY RAINAashrayraina22@gmail.com 7780995937...
7     Ramachandran IyerIIM Ahmedabad Alumnus| SMP | ...
8     Himanshu TyagiPune, Maharashtra - Email me on ...
9     Jalpa DaveData Scientist - Elegant Microweb Te...
10    Kishore Ramiyengar LakshmipprasannaC 404, Gaan...
11    Mohnish ChaudharyDECISION SCIENTIST - MU SIGMA...
12    Pawan Kumar Apawan9964@gmail.com#45, 8th cross...
13    Prikshit SharmaJammu,India prikshitsharma8024@...
14    Priyanka SrivastavaData ScientistData Science ...
15    Rakshit KhajuriaMachine Learning EngineerA 2+ ...
16    Rakshit KhajuriaMachine Learning EngineerTalab...
17    S W A Y A M G U P T A Jammu DOB: 9-Jan-200

In [20]:
cv_data=[]
for i in range(len(df["All"])):
    NLP_Processed_cv=nlp(df["All"].values[i])
    cv_data.append(NLP_Processed_cv)

In [21]:
cv_data

[['sukanya',
  'jangrabhiwani',
  'haryanajangrasukanya066',
  'gmail.compersonal',
  'detailsdate',
  'birth',
  '2003-11-24eligible',
  'work',
  'indiahighest',
  'career',
  'level',
  'fresherindustry',
  'internet',
  'ecommercework',
  'experiencecomputer',
  'operatoreducationbachelorsskills',
  'skill',
  'computer',
  'skill',
  'data',
  'entry',
  'typing',
  'customer',
  'service',
  'microsoft',
  'word',
  'microsoft',
  'excel',
  'microsoft',
  'office',
  'html',
  'javascript',
  'c',
  'c++certifications',
  'licensesdiploma',
  'computer',
  'applicationjanuary',
  '2021',
  'april',
  '2022'],
 ['abhay',
  'kumarlead',
  'data',
  'scientist',
  'computer',
  'visionbangalore|+91-9731-812-812',
  '|abhayownsthis',
  'gmail.com',
  'in.linkedin.com/in/abhay-kumar-99780458',
  'abhaymise.github.io/summary',
  'skillsi',
  'applied',
  'computer',
  'vision',
  'data',
  'scientist',
  'experience',
  'leading',
  'bunch',
  'core',
  'pythonother',
  'data',
  'sci

In [22]:
cv_=[]
for i in cv_data:
    cv_.append([' '.join(i)])

In [23]:
cv_

[['sukanya jangrabhiwani haryanajangrasukanya066 gmail.compersonal detailsdate birth 2003-11-24eligible work indiahighest career level fresherindustry internet ecommercework experiencecomputer operatoreducationbachelorsskills skill computer skill data entry typing customer service microsoft word microsoft excel microsoft office html javascript c c++certifications licensesdiploma computer applicationjanuary 2021 april 2022'],
 ["abhay kumarlead data scientist computer visionbangalore|+91-9731-812-812 |abhayownsthis gmail.com in.linkedin.com/in/abhay-kumar-99780458 abhaymise.github.io/summary skillsi applied computer vision data scientist experience leading bunch core pythonother data scientist used leadership applied deep learning skill successfullyexecute various computer vision project highly skilled applied deep learning computervision good understanding various computer vision technique like classification boundingbox classification regression object detection pixel wise prediction 

In [24]:
df["clean_all"]=pd.DataFrame(cv_)

# Recomendation Function

In [25]:
df.head(1)

Unnamed: 0            name                       email mobile_number  \
0           0  Sukanya Jangra  Jangrasukanya066@gmail.com           NaN   

                                              skills degree  no_of_pages  \
0  ['Data entry', 'Microsoft excel', 'Word', 'Htm...   None            1   

                                           file_path  \
0  cv_to_df/3bdfa685-56f1-4f83-866c-dbb20be51048.pdf   

                                                 All  \
0  Sukanya JangraBhiwani, HaryanaJangrasukanya066...   

                                           clean_all  
0  sukanya jangrabhiwani haryanajangrasukanya066 ...

In [26]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['name', 'degree',"email",'Unnamed: 0','mobile_number','skills','no_of_pages','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        
        recommendation.at[count, 'name'] = df['name'][i]
        recommendation.at[count, 'degree'] = df['degree'][i]
        recommendation.at[count, 'email'] = df['email'][i]
        recommendation.at[count, 'Unnamed: 0'] = df.index[i]
        recommendation.at[count, 'mobile_number'] = df['mobile_number'][i]
        recommendation.at[count, 'skills'] = df['skills'][i]
        recommendation.at[count, 'no_of_pages'] = df['no_of_pages'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

# cosine_similarity + TfidfVectorizer function

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    


In [28]:
output2 = TFIDF(df["clean_all"],jd_df['jd'])

In [29]:
output2 

[array([[0.04568556]]),
 array([[0.1143695]]),
 array([[0.16075353]]),
 array([[0.14300357]]),
 array([[0.15321865]]),
 array([[0.06769716]]),
 array([[0.06834925]]),
 array([[0.08622348]]),
 array([[0.17343765]]),
 array([[0.12146198]]),
 array([[0.15960294]]),
 array([[0.08172688]]),
 array([[0.07650771]]),
 array([[0.10592518]]),
 array([[0.07856661]]),
 array([[0.09510244]]),
 array([[0.1168029]]),
 array([[0.05733861]])]

In [30]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

name                                             degree  \
0        Himanshu Tyagi                           ['BTech in Electronics']   
1     Abhijit Manepatil  ['Master of Engineering', 'Master in Computer ...   
2    Kishore Ramiyengar                 ['Bachelor of Technology (Civil)']   
3        Aniket Kashyap  ['Bachelor of Engineering, Computer Science  n...   
4      Abhinav Abhishek                                               None   
5            Jalpa Dave                     ['B.E. in Computer', 'M.Tech']   
6      Rakshit Khajuria  ['Electronics and Communication, Engineering S...   
7           Abhay Kumar  ['e-commerce', 'Bachelor of Engineering,Comput...   
8       Prikshit Sharma      ['B Tech, Shri Mata Vaishno Devi University']   
9      Rakshit Khajuria  ['Electronics and Communication nEngineering S...   
10    Ramachandran Iyer                          ['Bachelors of Commerce']   
11    Mohnish Chaudhary                   ['BE in Information Technology']   
12  Priyanka Srivastava  ['PG certication in Data Science & MLnAcadgild...   
13        Pawan Kumar A  ['Bachelor of Science (Btech) in Computer Scie...   
14         ASHRAY RAINA                                         ['B.tech']   
15        Anirudh Anand                                               None   
16                  S W                        ['Bachelors of Technology']   
17       Sukanya Jangra                                               None   

                           email Unnamed: 0 mobile_number  \
0                            NaN          8    0800189689   
1                            NaN          2           NaN   
2         kishor.priya@gmail.com         10      007-2008   
3          monu.aniket@gmail.com          4    9691316944   
4            abhi4navv@gmail.com          3    8757656959   
5                            NaN          9           NaN   
6     rakshitraina1234@gmail.com         16    9149556155   
7        abhayownsthis@gmail.com          1       9978045   
8   prikshitsharma8024@gmail.com         13    7780992150   
9     rakshitraina1234@gmail.com         15    9149556155   
10          Ganesh2480@gmail.com          7    9820463399   
11                           NaN         11           NaN   
12    priyankasrvstv16@gmail.com         14    8948669980   
13           pawan9964@gmail.com         12    8008636324   
14       ashrayraina22@gmail.com          6    7780995937   
15      anirudhanand80@gmail.com          5    8082366408   
16       swayamgupta74@gmail.com         17    9797402957   
17    Jangrasukanya066@gmail.com          0           NaN   

                                               skills no_of_pages     score  
0   ['Electronics', 'Sales', 'Analytical', 'Email'...           2  0.173438  
1   ['Marketing', 'R', 'Mining', 'Email', 'Keras',...           3  0.160754  
2   ['Technical', 'Analyze', 'Sales', 'Finance', '...           9  0.159603  
3   ['Technical', 'Spyder', 'Mining', 'Keras', 'Em...           3  0.153219  
4   ['Electronics', 'Spyder', 'Sales', 'Mining', '...           3  0.143004  
5   ['Technical', 'Analyze', 'Marketing', 'R', 'Em...           3  0.121462  
6   ['Electronics', 'Analyze', 'Textblob', 'Coding...           2  0.116803  
7   ['Technical', 'R', 'Analytical', 'Keras', 'Ui'...           4  0.114369  
8   ['Electronics', 'Analytical', 'Sql', 'Programm...           2  0.105925  
9   ['Electronics', 'Seaborn', 'Tensorflow', 'Metr...           1  0.095102  
10  ['Technical', 'Crm', 'Itil', 'Sales', 'Project...           2  0.086223  
11  ['Technical', 'Gensim', 'Email', 'Mining', 'He...           3  0.081727  
12  ['Pandas', 'Analytics', 'System', 'Python', 'J...           1  0.078567  
13  ['Technical', 'R', 'Analytical', 'Keras', 'Sec...           2  0.076508  
14  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...           1  0.068349  
15  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...           2  0.067697  
16  ['Keras', 'Sql', 'Database', 'Programming', 'L

In [31]:
df

Unnamed: 0                 name                         email  \
0            0       Sukanya Jangra    Jangrasukanya066@gmail.com   
1            1          Abhay Kumar       abhayownsthis@gmail.com   
2            2    Abhijit Manepatil                           NaN   
3            3     Abhinav Abhishek           abhi4navv@gmail.com   
4            4       Aniket Kashyap         monu.aniket@gmail.com   
5            5        Anirudh Anand      anirudhanand80@gmail.com   
6            6         ASHRAY RAINA       ashrayraina22@gmail.com   
7            7    Ramachandran Iyer          Ganesh2480@gmail.com   
8            8       Himanshu Tyagi                           NaN   
9            9           Jalpa Dave                           NaN   
10          10   Kishore Ramiyengar        kishor.priya@gmail.com   
11          11    Mohnish Chaudhary                           NaN   
12          12        Pawan Kumar A           pawan9964@gmail.com   
13          13      Prikshit Sharma  prikshitsharma8024@gmail.com   
14          14  Priyanka Srivastava    priyankasrvstv16@gmail.com   
15          15     Rakshit Khajuria    rakshitraina1234@gmail.com   
16          16     Rakshit Khajuria    rakshitraina1234@gmail.com   
17          17                  S W       swayamgupta74@gmail.com   

   mobile_number                                             skills  \
0            NaN  ['Data entry', 'Microsoft excel', 'Word', 'Htm...   
1        9978045  ['Technical', 'R', 'Analytical', 'Keras', 'Ui'...   
2            NaN  ['Marketing', 'R', 'Mining', 'Email', 'Keras',...   
3     8757656959  ['Electronics', 'Spyder', 'Sales', 'Mining', '...   
4     9691316944  ['Technical', 'Spyder', 'Mining', 'Keras', 'Em...   
5     8082366408  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...   
6     7780995937  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...   
7     9820463399  ['Technical', 'Crm', 'Itil', 'Sales', 'Project...   
8     0800189689  ['Electronics', 'Sales', 'Analytical', 'Email'...   
9            NaN  ['Technical', 'Analyze', 'Marketing', 'R', 'Em...   
10      007-2008  ['Technical', 'Analyze', 'Sales', 'Finance', '...   
11           NaN  ['Technical', 'Gensim', 'Email', 'Mining', 'He...   
12    8008636324  ['Technical', 'R', 'Analytical', 'Keras', 'Sec...   
13    7780992150  ['Electronics', 'Analytical', 'Sql', 'Programm...   
14    8948669980  ['Pandas', 'Analytics', 'System', 'Python', 'J...   
15    9149556155  ['Electronics', 'Seaborn', 'Tensorflow', 'Metr...   
16    9149556155  ['Electronics', 'Analyze', 'Textblob', 'Coding...   
17    9797402957  ['Keras', 'Sql', 'Database', 'Programming', 'L...   

                                               degree  no_of_pages  \
0                                                None            1   
1   ['e-commerce', 'Bachelor of Engineering,Comput...            4   
2   ['Master of Engineering', 'Master in Computer ...            3   
3                                                None            3   
4   ['Bachelor of Engineering, Computer Science  n...            3   
5                                                None            2   
6                                          ['B.tech']            1   
7                           ['Bachelors of Commerce']            2   
8                            ['BTech in Electronics']            2   
9                      ['B.E. in Computer', 'M.Tech']            3   
10                 ['Bachelor of Technology (Civil)']            9   
11                   ['BE in Information Technology']            3   
12  ['Bachelor of Science (Btech) in Computer Scie...            2   
13      ['B Tech, Shri Mata Vaishno Devi University']            2   
14  ['PG certication in Data Science & MLnAcadgild...            1   
15  ['Electronics and Communication nEngineering S...            1   
16  ['Electronics and Communication, Engineering S...            2   
17                        ['Bachelors of Technology']            1   

           

# cosine_similarity + CountVectorizer


In [32]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df["clean_all"]) #converting job data into vectors using count vectorizers
count_jobid

<18x2933 sparse matrix of type '<class 'numpy.int64'>'
	with 5018 stored elements in Compressed Sparse Row format>

In [33]:
user_count = count_vectorizer.transform(jd_df['jd'])#converting user cv data into vectors using count vectorizers
user_count

<1x2933 sparse matrix of type '<class 'numpy.int64'>'
	with 45 stored elements in Compressed Sparse Row format>

In [34]:
print(user_count)

  (0, 439)	1
  (0, 474)	1
  (0, 493)	2
  (0, 529)	1
  (0, 697)	1
  (0, 754)	1
  (0, 812)	7
  (0, 817)	1
  (0, 893)	1
  (0, 934)	1
  (0, 1007)	1
  (0, 1054)	7
  (0, 1231)	2
  (0, 1574)	2
  (0, 1750)	1
  (0, 1768)	1
  (0, 1793)	1
  (0, 1829)	1
  (0, 1903)	1
  (0, 1991)	1
  (0, 2079)	1
  (0, 2110)	1
  (0, 2146)	2
  (0, 2173)	1
  (0, 2187)	1
  (0, 2237)	1
  (0, 2238)	1
  (0, 2252)	1
  (0, 2280)	1
  (0, 2374)	1
  (0, 2377)	1
  (0, 2411)	2
  (0, 2457)	1
  (0, 2469)	1
  (0, 2501)	1
  (0, 2602)	1
  (0, 2626)	1
  (0, 2674)	1
  (0, 2683)	1
  (0, 2694)	1
  (0, 2764)	1
  (0, 2795)	1
  (0, 2865)	1
  (0, 2908)	2
  (0, 2914)	1


In [35]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
#output3

In [36]:
output3 

[array([[0.13197176]]),
 array([[0.2605031]]),
 array([[0.35294448]]),
 array([[0.24849157]]),
 array([[0.25715623]]),
 array([[0.20724366]]),
 array([[0.19682149]]),
 array([[0.1398248]]),
 array([[0.36661899]]),
 array([[0.1749611]]),
 array([[0.2923324]]),
 array([[0.26077853]]),
 array([[0.17305804]]),
 array([[0.22971696]]),
 array([[0.2469171]]),
 array([[0.19962292]]),
 array([[0.21822742]]),
 array([[0.15192354]])]

In [37]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

name                                             degree  \
0        Himanshu Tyagi                           ['BTech in Electronics']   
1     Abhijit Manepatil  ['Master of Engineering', 'Master in Computer ...   
2    Kishore Ramiyengar                 ['Bachelor of Technology (Civil)']   
3     Mohnish Chaudhary                   ['BE in Information Technology']   
4           Abhay Kumar  ['e-commerce', 'Bachelor of Engineering,Comput...   
5        Aniket Kashyap  ['Bachelor of Engineering, Computer Science  n...   
6      Abhinav Abhishek                                               None   
7   Priyanka Srivastava  ['PG certication in Data Science & MLnAcadgild...   
8       Prikshit Sharma      ['B Tech, Shri Mata Vaishno Devi University']   
9      Rakshit Khajuria  ['Electronics and Communication, Engineering S...   
10        Anirudh Anand                                               None   
11     Rakshit Khajuria  ['Electronics and Communication nEngineering S...   
12         ASHRAY RAINA                                         ['B.tech']   
13           Jalpa Dave                     ['B.E. in Computer', 'M.Tech']   
14        Pawan Kumar A  ['Bachelor of Science (Btech) in Computer Scie...   
15                  S W                        ['Bachelors of Technology']   
16    Ramachandran Iyer                          ['Bachelors of Commerce']   
17       Sukanya Jangra                                               None   

                           email Unnamed: 0 mobile_number  \
0                            NaN          8    0800189689   
1                            NaN          2           NaN   
2         kishor.priya@gmail.com         10      007-2008   
3                            NaN         11           NaN   
4        abhayownsthis@gmail.com          1       9978045   
5          monu.aniket@gmail.com          4    9691316944   
6            abhi4navv@gmail.com          3    8757656959   
7     priyankasrvstv16@gmail.com         14    8948669980   
8   prikshitsharma8024@gmail.com         13    7780992150   
9     rakshitraina1234@gmail.com         16    9149556155   
10      anirudhanand80@gmail.com          5    8082366408   
11    rakshitraina1234@gmail.com         15    9149556155   
12       ashrayraina22@gmail.com          6    7780995937   
13                           NaN          9           NaN   
14           pawan9964@gmail.com         12    8008636324   
15       swayamgupta74@gmail.com         17    9797402957   
16          Ganesh2480@gmail.com          7    9820463399   
17    Jangrasukanya066@gmail.com          0           NaN   

                                               skills no_of_pages     score  
0   ['Electronics', 'Sales', 'Analytical', 'Email'...           2  0.366619  
1   ['Marketing', 'R', 'Mining', 'Email', 'Keras',...           3  0.352944  
2   ['Technical', 'Analyze', 'Sales', 'Finance', '...           9  0.292332  
3   ['Technical', 'Gensim', 'Email', 'Mining', 'He...           3  0.260779  
4   ['Technical', 'R', 'Analytical', 'Keras', 'Ui'...           4  0.260503  
5   ['Technical', 'Spyder', 'Mining', 'Keras', 'Em...           3  0.257156  
6   ['Electronics', 'Spyder', 'Sales', 'Mining', '...           3  0.248492  
7   ['Pandas', 'Analytics', 'System', 'Python', 'J...           1  0.246917  
8   ['Electronics', 'Analytical', 'Sql', 'Programm...           2  0.229717  
9   ['Electronics', 'Analyze', 'Textblob', 'Coding...           2  0.218227  
10  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...           2  0.207244  
11  ['Electronics', 'Seaborn', 'Tensorflow', 'Metr...           1  0.199623  
12  ['Pandas', 'Python', 'Algorithms', 'Numpy', 'S...           1  0.196821  
13  ['Technical', 'Analyze', 'Marketing', 'R', 'Em...           3  0.174961  
14  ['Technical', 'R', 'Analytical', 'Keras', 'Sec...           2  0.173058  
15  ['Keras', 'Sql', 'Database', 'Programming', 'L...           1  0.151924  
16  ['Technical', 'Crm', 'Itil', 'Sales', 'Project

# TfidfVectorizer + NearestNeighbors

In [38]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    
    KNN = NearestNeighbors(n_neighbors=7,p=2)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['clean_all'], jd_df['jd'])
knn

name                                             degree  \
0   Abhijit Manepatil  ['Master of Engineering', 'Master in Computer ...   
1  Kishore Ramiyengar                 ['Bachelor of Technology (Civil)']   
2      Aniket Kashyap  ['Bachelor of Engineering, Computer Science  n...   
3    Abhinav Abhishek                                               None   
4          Jalpa Dave                     ['B.E. in Computer', 'M.Tech']   
5    Rakshit Khajuria  ['Electronics and Communication, Engineering S...   

                        email Unnamed: 0 mobile_number  \
0                         NaN          2           NaN   
1      kishor.priya@gmail.com         10      007-2008   
2       monu.aniket@gmail.com          4    9691316944   
3         abhi4navv@gmail.com          3    8757656959   
4                         NaN          9           NaN   
5  rakshitraina1234@gmail.com         16    9149556155   

                                              skills no_of_pages     score  
0  ['Marketing', 'R', 'Mining', 'Email', 'Keras',...           3  1.295567  
1  ['Technical', 'Analyze', 'Sales', 'Finance', '...           9  1.296454  
2  ['Technical', 'Spyder', 'Mining', 'Keras', 'Em...           3   1.30137  
3  ['Electronics', 'Spyder', 'Sales', 'Mining', '...           3  1.309196  
4  ['Technical', 'Analyze', 'Marketing', 'R', 'Em...           3  1.325547  
5  ['Electronics', 'Analyze', 'Textblob', 'Coding...           2  1.329058

In [39]:

knn.to_csv('knn_cv.csv', index=False)

# Combined TFIDF, CV and KNN result together, to make a dataframe "final"

In [40]:
knn.columns

Index(['name', 'degree', 'email', 'Unnamed: 0', 'mobile_number', 'skills',
       'no_of_pages', 'score'],
      dtype='object')

In [41]:
merge1 = knn[['Unnamed: 0','name', 'score']].merge(TF[['Unnamed: 0','score']], on= "Unnamed: 0")
final = merge1.merge(cv[['Unnamed: 0','score']], on = 'Unnamed: 0')
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

Unnamed: 0                name       KNN    TF-IDF        CV
0          2   Abhijit Manepatil  1.295567  0.160754  0.352944
1         10  Kishore Ramiyengar  1.296454  0.159603  0.292332
2          4      Aniket Kashyap   1.30137  0.153219  0.257156
3          3    Abhinav Abhishek  1.309196  0.143004  0.248492
4          9          Jalpa Dave  1.325547  0.121462  0.174961

In [42]:
final

Unnamed: 0                name       KNN    TF-IDF        CV
0          2   Abhijit Manepatil  1.295567  0.160754  0.352944
1         10  Kishore Ramiyengar  1.296454  0.159603  0.292332
2          4      Aniket Kashyap   1.30137  0.153219  0.257156
3          3    Abhinav Abhishek  1.309196  0.143004  0.248492
4          9          Jalpa Dave  1.325547  0.121462  0.174961
5         16    Rakshit Khajuria  1.329058  0.116803  0.218227

In [43]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

Unnamed: 0                name       KNN    TF-IDF        CV     Final
0          2   Abhijit Manepatil  0.333333  0.333333  0.333333  1.000000
1         10  Kishore Ramiyengar  0.324497  0.324607  0.219817  0.868921
2          4      Aniket Kashyap  0.275577  0.276187  0.153938  0.705702
3          3    Abhinav Abhishek  0.197686  0.198713  0.137710  0.534110
5         16    Rakshit Khajuria  0.000000  0.000000  0.081031  0.081031
4          9          Jalpa Dave  0.034937  0.035336  0.000000  0.070272

In [44]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

Unnamed: 0                name       KNN    TF-IDF        CV     Final
0          2   Abhijit Manepatil  0.333333  0.333333  0.333333  1.000000
1         10  Kishore Ramiyengar  0.324497  0.324607  0.219817  0.868921
2          4      Aniket Kashyap  0.275577  0.276187  0.153938  0.705702
3          3    Abhinav Abhishek  0.197686  0.198713  0.137710  0.534110
5         16    Rakshit Khajuria  0.000000  0.000000  0.081031  0.081031
4          9          Jalpa Dave  0.034937  0.035336  0.000000  0.070272

In [45]:
# final2.merge(df, on="JobID")
final_df = df.merge(final2, on='Unnamed: 0')
final_df

Unnamed: 0              name_x                       email mobile_number  \
0          2   Abhijit Manepatil                         NaN           NaN   
1          3    Abhinav Abhishek         abhi4navv@gmail.com    8757656959   
2          4      Aniket Kashyap       monu.aniket@gmail.com    9691316944   
3          9          Jalpa Dave                         NaN           NaN   
4         10  Kishore Ramiyengar      kishor.priya@gmail.com      007-2008   
5         16    Rakshit Khajuria  rakshitraina1234@gmail.com    9149556155   

                                              skills  \
0  ['Marketing', 'R', 'Mining', 'Email', 'Keras',...   
1  ['Electronics', 'Spyder', 'Sales', 'Mining', '...   
2  ['Technical', 'Spyder', 'Mining', 'Keras', 'Em...   
3  ['Technical', 'Analyze', 'Marketing', 'R', 'Em...   
4  ['Technical', 'Analyze', 'Sales', 'Finance', '...   
5  ['Electronics', 'Analyze', 'Textblob', 'Coding...   

                                              degree  no_of_pages  \
0  ['Master of Engineering', 'Master in Computer ...            3   
1                                               None            3   
2  ['Bachelor of Engineering, Computer Science  n...            3   
3                     ['B.E. in Computer', 'M.Tech']            3   
4                 ['Bachelor of Technology (Civil)']            9   
5  ['Electronics and Communication, Engineering S...            2   

                                           file_path  \
0                     cv_to_df/Abhijit-Manepatil.pdf   
1  cv_to_df/Abhinav_Abhishek_visualcv_resume (1).pdf   
2                             cv_to_df/Aniket_cv.pdf   
3                            cv_to_df/Jalpa-Dave.pdf   
4               cv_to_df/Kishore_Ramiyengar_L_CV.pdf   
5               cv_to_df/rakshit_khajuria_resume.pdf   

                                                 All  \
0  Abhijit ManepatilData Scientist with Master in...   
1  Abhinav AbhishekSenior Software Developer/Data...   
2  Aniket KashyapSoftware Developer/Data Scientis...   
3  Jalpa DaveData Scientist - Elegant Microweb Te...   
4  Kishore Ramiyengar LakshmipprasannaC 404, Gaan...   
5  Rakshit KhajuriaMachine Learning EngineerTalab...   

                                           clean_all              name_y  \
0  abhijit manepatildata scientist master compute...   Abhijit Manepatil   
1  abhinav abhisheksenior software developer/data...    Abhinav Abhishek   
2  aniket kashyapsoftware developer/data scientis...      Aniket Kashyap   
3  jalpa davedata scientist elegant microweb tech...          Jalpa Dave   
4  kishore ramiyengar lakshmipprasannac 404 gaana...  Kishore Ramiyengar   
5  rakshit khajuriamachine learning engineertalab...    Rakshit Khajuria   

        KNN    TF-IDF        CV     Final  
0  0.333333  0.333333  0.333333  1.000000  
1  0.197686  0.198713  0.137710  0.534110  
2  0.275577  0.276187  0.153938  0.705702  
3  0.034937  0.035336  0.000000  0.070272  
4  0.324497  0.324607  0.219817  0.868921  
5  0.000000  0.000000  0.081031  0.081031

In [157]:
df.columns

Index(['Unnamed: 0', 'name', 'email', 'mobile_number', 'skills', 'degree',
       'no_of_pages', 'file_path', 'All', 'clean_all'],
      dtype='object')

In [46]:
final_df.columns

Index(['Unnamed: 0', 'name_x', 'email', 'mobile_number', 'skills', 'degree',
       'no_of_pages', 'file_path', 'All', 'clean_all', 'name_y', 'KNN',
       'TF-IDF', 'CV', 'Final'],
      dtype='object')

In [47]:
final_df

Unnamed: 0              name_x                       email mobile_number  \
0          2   Abhijit Manepatil                         NaN           NaN   
1          3    Abhinav Abhishek         abhi4navv@gmail.com    8757656959   
2          4      Aniket Kashyap       monu.aniket@gmail.com    9691316944   
3          9          Jalpa Dave                         NaN           NaN   
4         10  Kishore Ramiyengar      kishor.priya@gmail.com      007-2008   
5         16    Rakshit Khajuria  rakshitraina1234@gmail.com    9149556155   

                                              skills  \
0  ['Marketing', 'R', 'Mining', 'Email', 'Keras',...   
1  ['Electronics', 'Spyder', 'Sales', 'Mining', '...   
2  ['Technical', 'Spyder', 'Mining', 'Keras', 'Em...   
3  ['Technical', 'Analyze', 'Marketing', 'R', 'Em...   
4  ['Technical', 'Analyze', 'Sales', 'Finance', '...   
5  ['Electronics', 'Analyze', 'Textblob', 'Coding...   

                                              degree  no_of_pages  \
0  ['Master of Engineering', 'Master in Computer ...            3   
1                                               None            3   
2  ['Bachelor of Engineering, Computer Science  n...            3   
3                     ['B.E. in Computer', 'M.Tech']            3   
4                 ['Bachelor of Technology (Civil)']            9   
5  ['Electronics and Communication, Engineering S...            2   

                                           file_path  \
0                     cv_to_df/Abhijit-Manepatil.pdf   
1  cv_to_df/Abhinav_Abhishek_visualcv_resume (1).pdf   
2                             cv_to_df/Aniket_cv.pdf   
3                            cv_to_df/Jalpa-Dave.pdf   
4               cv_to_df/Kishore_Ramiyengar_L_CV.pdf   
5               cv_to_df/rakshit_khajuria_resume.pdf   

                                                 All  \
0  Abhijit ManepatilData Scientist with Master in...   
1  Abhinav AbhishekSenior Software Developer/Data...   
2  Aniket KashyapSoftware Developer/Data Scientis...   
3  Jalpa DaveData Scientist - Elegant Microweb Te...   
4  Kishore Ramiyengar LakshmipprasannaC 404, Gaan...   
5  Rakshit KhajuriaMachine Learning EngineerTalab...   

                                           clean_all              name_y  \
0  abhijit manepatildata scientist master compute...   Abhijit Manepatil   
1  abhinav abhisheksenior software developer/data...    Abhinav Abhishek   
2  aniket kashyapsoftware developer/data scientis...      Aniket Kashyap   
3  jalpa davedata scientist elegant microweb tech...          Jalpa Dave   
4  kishore ramiyengar lakshmipprasannac 404 gaana...  Kishore Ramiyengar   
5  rakshit khajuriamachine learning engineertalab...    Rakshit Khajuria   

        KNN    TF-IDF        CV     Final  
0  0.333333  0.333333  0.333333  1.000000  
1  0.197686  0.198713  0.137710  0.534110  
2  0.275577  0.276187  0.153938  0.705702  
3  0.034937  0.035336  0.000000  0.070272  
4  0.324497  0.324607  0.219817  0.868921  
5  0.000000  0.000000  0.081031  0.081031