In [180]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [181]:
# Import CV
f=open('textfile.txt','r', errors = 'ignore')
text=f.read()

In [182]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’'))
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [183]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [184]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['rakshit',
 'khajuriamachine',
 'learning',
 'engineertalab',
 'tillo',
 'gole',
 'gujral',
 '180002',
 'jammu',
 'india',
 'rakshitraina1234',
 'gmail.com',
 '914955615514',
 'aug',
 '2001',
 'http',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/',
 'http',
 '//github.com/ryzxxl9149556155summaryskilled',
 'developing',
 'implementing',
 'data-driven',
 'solution',
 'real-world',
 'problem',
 'utilizing',
 'range',
 'tool',
 'andtechniques',
 'extract',
 'valuable',
 'insight',
 'large',
 'complex',
 'data',
 'set',
 'posse',
 'diverse',
 'experience',
 'cleaningand',
 'analyzing',
 'data',
 'enhancing',
 'existing',
 'model',
 'continuously',
 'seeking',
 'enhance',
 'skill',
 'broaden',
 'myknowledge',
 'dynamic',
 '\x00eld',
 'data',
 'science.skillstools',
 'python',
 'git',
 'github',
 'jupyter',
 'notebook',
 'anaconda',
 'v',
 'codepackages',
 'scikit-learn',
 'numpy',
 'panda',
 'matplotlib',
 'nltk',
 'tensorflow',
 'flask',
 'streamlit',
 'spacy',
 'text',
 'blob',
 'va

In [185]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(('\x00eld', 'data'), 2)
(('\x00ne-tuning', 'pre-trained'), 2)
(('.', 'transformer'), 2)
(('.improved', 'model'), 2)
(('//github.com/ryzxxl9149556155summaryskilled', 'developing'), 2)
(('//www.linkedin.com/in/rakshit-khajuria-3627781b8/', 'http'), 2)
(('180002', 'jammu'), 2)
(('2001', 'http'), 2)
(('2020', 'aug'), 2)
(('2021became', 'pro\x00cient'), 2)
(('2022', 'presentjammu'), 2)
(('914955615514', 'aug'), 2)
(('accuracy', 'applying'), 2)
(('accurately', 'analyze'), 2)
(('advanced', 'technique'), 2)
(('algorithm', 'decision'), 2)
(('algorithm', 'e.g'), 2)
(('algorithm', 'including'), 2)
(('anaconda', 'v'), 2)
(('analysis', 'model'), 2)
(('analysis', 'text'), 2)
(('analyze', 'andinterpret'), 2)
(('analyzing', 'data'), 2)
(('andinterpret', 'sentiment.enhanced'), 2)
(('andtechniques', 'extract'), 2)
(('applying', 'different'), 2)
(('aslstm', 'bilstm'), 2)
(('aug', '2001'), 2)
(('aug', '2021became'), 2)
(('aws', 'ef\x00ciently'), 2)
(('bangalore', 'indiaunderlying'), 2)
(('bert', 'lstms')

['\x00eld data',
 '\x00ne-tuning pre-trained',
 '. transformer',
 '.improved model',
 '//github.com/ryzxxl9149556155summaryskilled developing',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/ http',
 '180002 jammu',
 '2001 http',
 '2020 aug',
 '2021became pro\x00cient',
 '2022 presentjammu',
 '914955615514 aug',
 'accuracy applying',
 'accurately analyze',
 'advanced technique',
 'algorithm decision',
 'algorithm e.g',
 'algorithm including',
 'anaconda v',
 'analysis model',
 'analysis text',
 'analyze andinterpret',
 'analyzing data',
 'andinterpret sentiment.enhanced',
 'andtechniques extract',
 'applying different',
 'aslstm bilstm',
 'aug 2001',
 'aug 2021became',
 'aws ef\x00ciently',
 'bangalore indiaunderlying',
 'bert lstms',
 'bert models.machine',
 'bilstm etc',
 'blob vader.machine',
 'broaden myknowledge',
 'classi\x00cation named',
 'classifyemotional context',
 'cleaningand analyzing',
 'cloud platform',
 'clustering algorithm',
 'codepackages scikit-learn',
 'comple

# Importing scapped df

In [186]:
DF_PATH = "data.csv"

In [187]:
df = pd.read_csv(DF_PATH)
df

id                                         company  \
0     2567a216d4af7021                                            AT&T   
1     442ad7cc38a6f7b8                           ICICI Prudential Life   
2     e0fe53f38f84e7bd                           ICICI Prudential Life   
3     363b96425a82d12d                                    TMI Group IN   
4     215ece39050fb3f5                   Shairu Gems Diamonds PVT.LTD.   
...                ...                                             ...   
5497  f53ad1277acdc74c                                   VISION ESTEEM   
5498  2b1b759b9c3a9246                                 L.R. Patel & Co   
5499  745a1ac63a001f46                Proactive Consultants & Services   
5500  d7901b874316b5d7  American Academy of Financial Management India   
5501  837f8b5ef252bcd0                          SV Placement Solutions   

                     positionName  \
0      SPECIALIST, DATA ANALYTICS   
1                  Data scientist   
2           Data scientist - Lead   
3                 Bot NLP Analyst   
4           Senior Data Scientist   
...                           ...   
5497           Executive HR Admin   
5498                 HR Recruiter   
5499                 HR Recruiter   
5500        Recruitment Executive   
5501  HR Recruiter (females only)   

                                            description  \
0     \n \n  Experienced data analyst position that ...   
1     Roles and responsibilities:\n 1. Data processi...   
2     Roles and responsibilities:\n 1. Data processi...   
3     \n Job Information \n \n \n  \n   \n    Salary...   
4     Sr. Data Analyst,\nShairu Gems Diamonds PVT. L...   
...                                                 ...   
5497  Urgently looking Executive HR and Admin for le...   
5498  JOB OVERVIEW: The HR Assistant duties involve ...   
5499  Dear candidates,\nWe have an urgent Opening fo...   
5500  Roles & Responsibilities :\nDesign and update ...   
5501  \n Partnering with hiring managers to determin...   

                              salary                location  rating  \
0                                NaN    Hyderabad, Telangana     3.7   
1                                NaN     Mumbai, Maharashtra     4.0   
2                                NaN     Mumbai, Maharashtra     4.0   
3     ₹10,00,000 - ₹16,00,000 a year    Hyderabad, Telangana     NaN   
4          ₹25,000 - ₹35,000 a month          Surat, Gujarat     NaN   
...                              ...                     ...     ...   
5497       ₹20,000 - ₹25,000 a month  Chandigarh, Chandigarh     NaN   
5498       ₹15,000 - ₹20,000 a month      Ahmedabad, Gujarat     NaN   
5499       ₹20,000 - ₹25,000 a month        New Delhi, Delhi     NaN   
5500       ₹20,000 - ₹25,000 a month            Delhi, Delhi     NaN   
5501        ₹8,000 - ₹12,000 a month         Patiala, Punjab     5.0   

      reviewsCount     postedAt  \
0          43942.0        Today   
1           1391.0  Just posted   
2           1391.0  Just posted   
3              NaN    1 day ago   
4              NaN        Today   
...            ...          ...   
5497           NaN   2 days ago   
5498           NaN   2 days ago   
5499           NaN   2 days ago   
5500           NaN   2 days ago   
5501           2.0   2 days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=2567a216d4...   
1     https://in.indeed.com/applystart?jk=442ad7cc38...   
2     https://in.indeed.com/applystart?jk=e0fe53f38f...   
3     https://in.indeed.com/applystart?jk=363b96425a...   
4                                                   NaN   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499                                                NaN   
5500                                                NaN   
5501                                      

In [232]:
df["JobID"]=df.index

In [233]:
df

id                                         company  \
0     2567a216d4af7021                                            AT&T   
1     442ad7cc38a6f7b8                           ICICI Prudential Life   
2     e0fe53f38f84e7bd                           ICICI Prudential Life   
3     363b96425a82d12d                                    TMI Group IN   
4     215ece39050fb3f5                   Shairu Gems Diamonds PVT.LTD.   
...                ...                                             ...   
5497  f53ad1277acdc74c                                   VISION ESTEEM   
5498  2b1b759b9c3a9246                                 L.R. Patel & Co   
5499  745a1ac63a001f46                Proactive Consultants & Services   
5500  d7901b874316b5d7  American Academy of Financial Management India   
5501  837f8b5ef252bcd0                          SV Placement Solutions   

                     positionName  \
0      SPECIALIST, DATA ANALYTICS   
1                  Data scientist   
2           Data scientist - Lead   
3                 Bot NLP Analyst   
4           Senior Data Scientist   
...                           ...   
5497           Executive HR Admin   
5498                 HR Recruiter   
5499                 HR Recruiter   
5500        Recruitment Executive   
5501  HR Recruiter (females only)   

                                            description  \
0     Experienced data analyst position that uses te...   
1     Roles and responsibilities: 1. Data processing...   
2     Roles and responsibilities: 1. Data processing...   
3     Job Information            Salary     ₹ 100000...   
4     Sr. Data Analyst,Shairu Gems Diamonds PVT. LTD...   
...                                                 ...   
5497  Urgently looking Executive HR and Admin for le...   
5498  JOB OVERVIEW: The HR Assistant duties involve ...   
5499  Dear candidates,We have an urgent Opening for ...   
5500  Roles & Responsibilities :Design and update jo...   
5501  Partnering with hiring managers to determine s...   

                              salary                location  rating  \
0                                NaN    Hyderabad, Telangana     3.7   
1                                NaN     Mumbai, Maharashtra     4.0   
2                                NaN     Mumbai, Maharashtra     4.0   
3     ₹10,00,000 - ₹16,00,000 a year    Hyderabad, Telangana     NaN   
4          ₹25,000 - ₹35,000 a month          Surat, Gujarat     NaN   
...                              ...                     ...     ...   
5497       ₹20,000 - ₹25,000 a month  Chandigarh, Chandigarh     NaN   
5498       ₹15,000 - ₹20,000 a month      Ahmedabad, Gujarat     NaN   
5499       ₹20,000 - ₹25,000 a month        New Delhi, Delhi     NaN   
5500       ₹20,000 - ₹25,000 a month            Delhi, Delhi     NaN   
5501        ₹8,000 - ₹12,000 a month         Patiala, Punjab     5.0   

      reviewsCount     postedAt  \
0          43942.0        Today   
1           1391.0  Just posted   
2           1391.0  Just posted   
3              NaN    1 day ago   
4              NaN        Today   
...            ...          ...   
5497           NaN   2 days ago   
5498           NaN   2 days ago   
5499           NaN   2 days ago   
5500           NaN   2 days ago   
5501           2.0   2 days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=2567a216d4...   
1     https://in.indeed.com/applystart?jk=442ad7cc38...   
2     https://in.indeed.com/applystart?jk=e0fe53f38f...   
3     https://in.indeed.com/applystart?jk=363b96425a...   
4                                                   NaN   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499                                                NaN   
5500                                                NaN   
5501                                      

In [234]:
df.shape


(5502, 13)

In [235]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 13 columns):
id                   5502 non-null object
company              5408 non-null object
positionName         5502 non-null object
description          5502 non-null object
salary               1248 non-null object
location             5502 non-null object
rating               3128 non-null float64
reviewsCount         3128 non-null float64
postedAt             5502 non-null object
externalApplyLink    4044 non-null object
url                  5502 non-null object
All                  5502 non-null object
JobID                5502 non-null int64
dtypes: float64(2), int64(1), object(10)
memory usage: 558.9+ KB


In [236]:
df['All'] = df[df.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)

In [237]:
df

id                                         company  \
0     2567a216d4af7021                                            AT&T   
1     442ad7cc38a6f7b8                           ICICI Prudential Life   
2     e0fe53f38f84e7bd                           ICICI Prudential Life   
3     363b96425a82d12d                                    TMI Group IN   
4     215ece39050fb3f5                   Shairu Gems Diamonds PVT.LTD.   
...                ...                                             ...   
5497  f53ad1277acdc74c                                   VISION ESTEEM   
5498  2b1b759b9c3a9246                                 L.R. Patel & Co   
5499  745a1ac63a001f46                Proactive Consultants & Services   
5500  d7901b874316b5d7  American Academy of Financial Management India   
5501  837f8b5ef252bcd0                          SV Placement Solutions   

                     positionName  \
0      SPECIALIST, DATA ANALYTICS   
1                  Data scientist   
2           Data scientist - Lead   
3                 Bot NLP Analyst   
4           Senior Data Scientist   
...                           ...   
5497           Executive HR Admin   
5498                 HR Recruiter   
5499                 HR Recruiter   
5500        Recruitment Executive   
5501  HR Recruiter (females only)   

                                            description  \
0     Experienced data analyst position that uses te...   
1     Roles and responsibilities: 1. Data processing...   
2     Roles and responsibilities: 1. Data processing...   
3     Job Information            Salary     ₹ 100000...   
4     Sr. Data Analyst,Shairu Gems Diamonds PVT. LTD...   
...                                                 ...   
5497  Urgently looking Executive HR and Admin for le...   
5498  JOB OVERVIEW: The HR Assistant duties involve ...   
5499  Dear candidates,We have an urgent Opening for ...   
5500  Roles & Responsibilities :Design and update jo...   
5501  Partnering with hiring managers to determine s...   

                              salary                location  rating  \
0                                NaN    Hyderabad, Telangana     3.7   
1                                NaN     Mumbai, Maharashtra     4.0   
2                                NaN     Mumbai, Maharashtra     4.0   
3     ₹10,00,000 - ₹16,00,000 a year    Hyderabad, Telangana     NaN   
4          ₹25,000 - ₹35,000 a month          Surat, Gujarat     NaN   
...                              ...                     ...     ...   
5497       ₹20,000 - ₹25,000 a month  Chandigarh, Chandigarh     NaN   
5498       ₹15,000 - ₹20,000 a month      Ahmedabad, Gujarat     NaN   
5499       ₹20,000 - ₹25,000 a month        New Delhi, Delhi     NaN   
5500       ₹20,000 - ₹25,000 a month            Delhi, Delhi     NaN   
5501        ₹8,000 - ₹12,000 a month         Patiala, Punjab     5.0   

      reviewsCount     postedAt  \
0          43942.0        Today   
1           1391.0  Just posted   
2           1391.0  Just posted   
3              NaN    1 day ago   
4              NaN        Today   
...            ...          ...   
5497           NaN   2 days ago   
5498           NaN   2 days ago   
5499           NaN   2 days ago   
5500           NaN   2 days ago   
5501           2.0   2 days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=2567a216d4...   
1     https://in.indeed.com/applystart?jk=442ad7cc38...   
2     https://in.indeed.com/applystart?jk=e0fe53f38f...   
3     https://in.indeed.com/applystart?jk=363b96425a...   
4                                                   NaN   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499                                                NaN   
5500                                                NaN   
5501                                      

In [238]:
df['All']

0       2567a216d4af7021,AT&T,SPECIALIST, DATA ANALYTI...
1       442ad7cc38a6f7b8,ICICI Prudential Life,Data sc...
2       e0fe53f38f84e7bd,ICICI Prudential Life,Data sc...
3       363b96425a82d12d,TMI Group IN,Bot NLP Analyst,...
4       215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD....
                              ...                        
5497    f53ad1277acdc74c,VISION ESTEEM,Executive HR Ad...
5498    2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,...
5499    745a1ac63a001f46,Proactive Consultants & Servi...
5500    d7901b874316b5d7,American Academy of Financial...
5501    837f8b5ef252bcd0,SV Placement Solutions,HR Rec...
Name: All, Length: 5502, dtype: object

In [239]:
df["description"].replace(r'\n','', regex=True,inplace=True)
df["description"].replace(r'\r','', regex=True,inplace=True)  
df = df.replace(' ', '')
df.description = df.description.str.strip()
df.All = df.All.str.strip()

In [240]:
df

id                                         company  \
0     2567a216d4af7021                                            AT&T   
1     442ad7cc38a6f7b8                           ICICI Prudential Life   
2     e0fe53f38f84e7bd                           ICICI Prudential Life   
3     363b96425a82d12d                                    TMI Group IN   
4     215ece39050fb3f5                   Shairu Gems Diamonds PVT.LTD.   
...                ...                                             ...   
5497  f53ad1277acdc74c                                   VISION ESTEEM   
5498  2b1b759b9c3a9246                                 L.R. Patel & Co   
5499  745a1ac63a001f46                Proactive Consultants & Services   
5500  d7901b874316b5d7  American Academy of Financial Management India   
5501  837f8b5ef252bcd0                          SV Placement Solutions   

                     positionName  \
0      SPECIALIST, DATA ANALYTICS   
1                  Data scientist   
2           Data scientist - Lead   
3                 Bot NLP Analyst   
4           Senior Data Scientist   
...                           ...   
5497           Executive HR Admin   
5498                 HR Recruiter   
5499                 HR Recruiter   
5500        Recruitment Executive   
5501  HR Recruiter (females only)   

                                            description  \
0     Experienced data analyst position that uses te...   
1     Roles and responsibilities: 1. Data processing...   
2     Roles and responsibilities: 1. Data processing...   
3     Job Information            Salary     ₹ 100000...   
4     Sr. Data Analyst,Shairu Gems Diamonds PVT. LTD...   
...                                                 ...   
5497  Urgently looking Executive HR and Admin for le...   
5498  JOB OVERVIEW: The HR Assistant duties involve ...   
5499  Dear candidates,We have an urgent Opening for ...   
5500  Roles & Responsibilities :Design and update jo...   
5501  Partnering with hiring managers to determine s...   

                              salary                location  rating  \
0                                NaN    Hyderabad, Telangana     3.7   
1                                NaN     Mumbai, Maharashtra     4.0   
2                                NaN     Mumbai, Maharashtra     4.0   
3     ₹10,00,000 - ₹16,00,000 a year    Hyderabad, Telangana     NaN   
4          ₹25,000 - ₹35,000 a month          Surat, Gujarat     NaN   
...                              ...                     ...     ...   
5497       ₹20,000 - ₹25,000 a month  Chandigarh, Chandigarh     NaN   
5498       ₹15,000 - ₹20,000 a month      Ahmedabad, Gujarat     NaN   
5499       ₹20,000 - ₹25,000 a month        New Delhi, Delhi     NaN   
5500       ₹20,000 - ₹25,000 a month            Delhi, Delhi     NaN   
5501        ₹8,000 - ₹12,000 a month         Patiala, Punjab     5.0   

      reviewsCount     postedAt  \
0          43942.0        Today   
1           1391.0  Just posted   
2           1391.0  Just posted   
3              NaN    1 day ago   
4              NaN        Today   
...            ...          ...   
5497           NaN   2 days ago   
5498           NaN   2 days ago   
5499           NaN   2 days ago   
5500           NaN   2 days ago   
5501           2.0   2 days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=2567a216d4...   
1     https://in.indeed.com/applystart?jk=442ad7cc38...   
2     https://in.indeed.com/applystart?jk=e0fe53f38f...   
3     https://in.indeed.com/applystart?jk=363b96425a...   
4                                                   NaN   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499                                                NaN   
5500                                                NaN   
5501                                      

# Put keywords of the CV into a dataframe

In [241]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

In [242]:
df2

title job highlights job description company overview industry  \
0     I              I               I                I        I   

                                                 All  
0  eld data ne-tuning pre-trained . transformer...

In [243]:
df.columns

Index(['id', 'company', 'positionName', 'description', 'salary', 'location',
       'rating', 'reviewsCount', 'postedAt', 'externalApplyLink', 'url', 'All',
       'JobID'],
      dtype='object')

# Recomendation Function

#klnsdsd

In [244]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['positionName', 'company',"location",'JobID','description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        
        recommendation.at[count, 'positionName'] = df['positionName'][i]
        recommendation.at[count, 'company'] = df['company'][i]
        recommendation.at[count, 'location'] = df['location'][i]
    
        recommendation.at[count, 'JobID'] = df.index[i]
        recommendation.at[count, 'description'] = df['description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

## cosine_similarity + TfidfVectorizer function

In [245]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])


In [246]:
len(output2)

5502

In [247]:
output2


[array([[0.09490157]]),
 array([[0.08463058]]),
 array([[0.08307375]]),
 array([[0.05026806]]),
 array([[0.02434449]]),
 array([[0.15048193]]),
 array([[0.14032287]]),
 array([[0.07494617]]),
 array([[0.09940794]]),
 array([[0.15000869]]),
 array([[0.12688779]]),
 array([[0.08432616]]),
 array([[0.10166767]]),
 array([[0.09765062]]),
 array([[0.00857239]]),
 array([[0.05933496]]),
 array([[0.07607672]]),
 array([[0.12224729]]),
 array([[0.06334636]]),
 array([[0.00537008]]),
 array([[0.05739081]]),
 array([[0.0707714]]),
 array([[0.0379942]]),
 array([[0.05863688]]),
 array([[0.05504226]]),
 array([[0.0577897]]),
 array([[0.1246984]]),
 array([[0.09503254]]),
 array([[0.14071974]]),
 array([[0.10674914]]),
 array([[0.02927092]]),
 array([[0.07472828]]),
 array([[0.08503921]]),
 array([[0.14455256]]),
 array([[0.08551474]]),
 array([[0.02367107]]),
 array([[0.07412153]]),
 array([[0.00932761]]),
 array([[0.04218153]]),
 array([[0.10972412]]),
 array([[0.04917929]]),
 array([[0.08881397]

In [248]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

positionName                  company  \
0                 Machine Learning Lead Engineer                   Wasoko   
1                                 Data Scientist  Chubb INA Holdings Inc.   
2                 Data Science - Knowledge Graph  Chubb INA Holdings Inc.   
3                    Manager MLOps, Data Science   Mondelēz International   
4                    Manager MLOps, Data Science   Mondelēz International   
..                                           ...                      ...   
95                                AI/ML Engineer                BizAcuity   
96                     Data Science (NLP) Intern               Emplay Inc   
97           Data Science and Business Analytics            Zotto Limited   
98  Lead Machine Learning Firmware Test Engineer                   Axiado   
99  Lead Machine Learning Firmware Test Engineer                   Axiado   

                location JobID  \
0   Bengaluru, Karnataka   480   
1   Bengaluru, Karnataka    91   
2   Bengaluru, Karnataka    95   
3    Mumbai, Maharashtra   382   
4    Mumbai, Maharashtra   982   
..                   ...   ...   
95                 India   917   
96                Remote   430   
97          Delhi, Delhi   306   
98  Hyderabad, Telangana   872   
99  Hyderabad, Telangana   338   

                                          description     score  
0   Summary  We are looking for an experienced ML ...  0.226897  
1   Job Requirements  Responsibilities Work with b...  0.218604  
2   Work Experience Work with business partners gl...  0.216358  
3   Job Description   Are You Ready to Make It Hap...   0.20882  
4   Job Description   Are You Ready to Make It Hap...  0.208813  
..                                                ...       ...  
95  Roles and Responsibilities Experience with Dee...  0.136698  
96  Job Title: NLP/Data Science InternStipend- 20,...  0.136235  
97  We are looking for a Data Scientist who will s...  0.136063  
98  Company Description  Axiado is an AI-enhanced ...  0.134897  
99  Company Description  Axiado is an AI-enhanced ...  0.134875  

[100 rows x 6 columns]

## cosine_similarity + CountVectorizer

In [249]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All']) #converting job data into vectors using count vectorizers
count_jobid

<5502x52637 sparse matrix of type '<class 'numpy.int64'>'
	with 1666676 stored elements in Compressed Sparse Row format>

In [250]:
# print(count_jobid)


In [251]:
user_count = count_vectorizer.transform(df2['All'])#converting user cv data into vectors using count vectorizers
user_count

<1x52637 sparse matrix of type '<class 'numpy.int64'>'
	with 153 stored elements in Compressed Sparse Row format>

In [252]:
print(user_count)


  (0, 2913)	2
  (0, 2967)	2
  (0, 2970)	2
  (0, 15813)	2
  (0, 15815)	2
  (0, 16168)	2
  (0, 16591)	5
  (0, 16821)	2
  (0, 16832)	3
  (0, 16871)	2
  (0, 16876)	2
  (0, 16949)	2
  (0, 17212)	2
  (0, 17818)	4
  (0, 17993)	2
  (0, 18627)	2
  (0, 19069)	4
  (0, 19369)	2
  (0, 22941)	2
  (0, 24943)	2
  (0, 24995)	3
  (0, 25239)	8
  (0, 25455)	2
  (0, 25554)	2
  (0, 25844)	2
  :	:
  (0, 48064)	4
  (0, 48334)	2
  (0, 48889)	2
  (0, 48929)	4
  (0, 49115)	2
  (0, 49211)	4
  (0, 49212)	2
  (0, 49590)	2
  (0, 49623)	1
  (0, 49653)	2
  (0, 49684)	2
  (0, 49812)	4
  (0, 49857)	2
  (0, 49940)	2
  (0, 50098)	2
  (0, 50537)	4
  (0, 50651)	2
  (0, 50672)	3
  (0, 50702)	2
  (0, 50704)	2
  (0, 50798)	2
  (0, 51749)	2
  (0, 51902)	4
  (0, 51986)	2
  (0, 52078)	2


In [253]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
#output3

In [254]:
output3

[array([[0.18863457]]),
 array([[0.2481385]]),
 array([[0.24711524]]),
 array([[0.12716114]]),
 array([[0.12939732]]),
 array([[0.23386668]]),
 array([[0.20115459]]),
 array([[0.20418955]]),
 array([[0.15770306]]),
 array([[0.23541296]]),
 array([[0.25059923]]),
 array([[0.18570229]]),
 array([[0.1823044]]),
 array([[0.23054604]]),
 array([[0.05574862]]),
 array([[0.07995794]]),
 array([[0.17876581]]),
 array([[0.30066768]]),
 array([[0.11702739]]),
 array([[0.05482444]]),
 array([[0.13573553]]),
 array([[0.15172343]]),
 array([[0.08835614]]),
 array([[0.17443657]]),
 array([[0.13318113]]),
 array([[0.22564303]]),
 array([[0.1761034]]),
 array([[0.1852207]]),
 array([[0.21421287]]),
 array([[0.16261891]]),
 array([[0.07621752]]),
 array([[0.17870924]]),
 array([[0.20435785]]),
 array([[0.26651071]]),
 array([[0.15601183]]),
 array([[0.09007552]]),
 array([[0.14537332]]),
 array([[0.07623741]]),
 array([[0.12837822]]),
 array([[0.21094625]]),
 array([[0.12037555]]),
 array([[0.20473648]

In [255]:
df.rating

0       3.7
1       4.0
2       4.0
3       NaN
4       NaN
       ... 
5497    NaN
5498    NaN
5499    NaN
5500    NaN
5501    5.0
Name: rating, Length: 5502, dtype: float64

In [256]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

positionName  \
0               Python Machine Learning Engineer   
1                      MACHINE LEARNING ENGINEER   
2                      MACHINE LEARNING ENGINEER   
3                  Data Scientist (India Remote)   
4                  Data Scientist (India Remote)   
..                                           ...   
95  Lead Machine Learning Firmware Test Engineer   
96                              Machine Learning   
97                     Machine Learning Engineer   
98                     Machine Learning Engineer   
99                                Data Scientist   

                         company              location JobID  \
0         Vingsfire HRIM Pvt Ltd   Madurai, Tamil Nadu   473   
1            Amanzi Technologies  Noida, Uttar Pradesh   400   
2            Amanzi Technologies  Noida, Uttar Pradesh   920   
3                  Token Metrics  Bengaluru, Karnataka    74   
4                  Token Metrics  Bengaluru, Karnataka   531   
..                           ...                   ...   ...   
95                        Axiado  Hyderabad, Telangana   872   
96     Think Future Technologies      Gurgaon, Haryana   352   
97                         Apple  Bengaluru, Karnataka   225   
98                         Apple  Bengaluru, Karnataka   710   
99  Ergode IT Services Pvt. ltd.   Mumbai, Maharashtra   327   

                                          description     score  
0   Role : Senior Python DeveloperExperience: 5+ Y...  0.360817  
1   Amanzi Technologies Pvt. Ltd.                 ...  0.357587  
2   Amanzi Technologies Pvt. Ltd.                 ...  0.357587  
3   Token Metrics is searching for a highly capabl...  0.356055  
4   Token Metrics is searching for a highly capabl...  0.356055  
..                                                ...       ...  
95  Company Description  Axiado is an AI-enhanced ...  0.237684  
96  Exp: 2 + Years  Location: Gurgaon/ Remote  Ski...  0.237348  
97  Summary                Posted: Dec 7, 2022    ...   0.23677  
98  Summary                Posted: Dec 7, 2022    ...   0.23677  
99  Role Description - (Mumbai Based and Immediate...  0.235978  

[100 rows x 6 columns]

In [257]:
cv.description[1]

'Amanzi Technologies Pvt. Ltd.                              Permanent                              Noida                              Posted 3 weeks ago                          Out of the box solution          Responsibilities:      Designing and developing machine learning and deep learning systems.    Running machine learning tests and experiments.    Implementing appropriate ML algorithms.        Job brief:   We are looking for a Machine Learning (ML) Engineer to help us create artificial intelligence products.   Machine Learning Engineer responsibilities include creating machine learning models and retraining systems. To do this job successfully, you need exceptional skills in statistics and programming. If you also have knowledge of data science and software engineering, we’d like to meet you.   Your ultimate goal will be to shape and build efficient self-learning applications.   Responsibilities:      Study and transform data science prototypes.    Design machine learning system

## TfidfVectorizer + NearestNeighbors

In [258]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    
    KNN = NearestNeighbors(n_neighbors=100,p=2)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

positionName                  company  \
0                                 Data Scientist  Chubb INA Holdings Inc.   
1                 Data Science - Knowledge Graph  Chubb INA Holdings Inc.   
2                    Manager MLOps, Data Science   Mondelēz International   
3                    Manager MLOps, Data Science   Mondelēz International   
4                      ASSOCIATE DEVOPS ENGINEER          SKS Enterpprise   
..                                           ...                      ...   
94                                AI/ML Engineer                BizAcuity   
95                     Data Science (NLP) Intern               Emplay Inc   
96           Data Science and Business Analytics            Zotto Limited   
97  Lead Machine Learning Firmware Test Engineer                   Axiado   
98  Lead Machine Learning Firmware Test Engineer                   Axiado   

                location JobID  \
0   Bengaluru, Karnataka    91   
1   Bengaluru, Karnataka    95   
2    Mumbai, Maharashtra   382   
3    Mumbai, Maharashtra   982   
4    Chennai, Tamil Nadu   779   
..                   ...   ...   
94                 India   917   
95                Remote   430   
96          Delhi, Delhi   306   
97  Hyderabad, Telangana   872   
98  Hyderabad, Telangana   338   

                                          description    score  
0   Job Requirements  Responsibilities Work with b...  1.25012  
1   Work Experience Work with business partners gl...  1.25191  
2   Job Description   Are You Ready to Make It Hap...  1.25792  
3   Job Description   Are You Ready to Make It Hap...  1.25792  
4   Position Name - Associate DevOps Engineer    L...  1.26779  
..                                                ...      ...  
94  Roles and Responsibilities Experience with Dee...    1.314  
95  Job Title: NLP/Data Science InternStipend- 20,...  1.31436  
96  We are looking for a Data Scientist who will s...  1.31449  
97  Company Description  Axiado is an AI-enhanced ...  1.31537  
98  Company Description  Axiado is an AI-enhanced ...  1.31539  

[99 rows x 6 columns]

In [259]:

knn.to_csv('knn.csv', index=False)

In [260]:
cv

positionName  \
0               Python Machine Learning Engineer   
1                      MACHINE LEARNING ENGINEER   
2                      MACHINE LEARNING ENGINEER   
3                  Data Scientist (India Remote)   
4                  Data Scientist (India Remote)   
..                                           ...   
95  Lead Machine Learning Firmware Test Engineer   
96                              Machine Learning   
97                     Machine Learning Engineer   
98                     Machine Learning Engineer   
99                                Data Scientist   

                         company              location JobID  \
0         Vingsfire HRIM Pvt Ltd   Madurai, Tamil Nadu   473   
1            Amanzi Technologies  Noida, Uttar Pradesh   400   
2            Amanzi Technologies  Noida, Uttar Pradesh   920   
3                  Token Metrics  Bengaluru, Karnataka    74   
4                  Token Metrics  Bengaluru, Karnataka   531   
..                           ...                   ...   ...   
95                        Axiado  Hyderabad, Telangana   872   
96     Think Future Technologies      Gurgaon, Haryana   352   
97                         Apple  Bengaluru, Karnataka   225   
98                         Apple  Bengaluru, Karnataka   710   
99  Ergode IT Services Pvt. ltd.   Mumbai, Maharashtra   327   

                                          description     score  
0   Role : Senior Python DeveloperExperience: 5+ Y...  0.360817  
1   Amanzi Technologies Pvt. Ltd.                 ...  0.357587  
2   Amanzi Technologies Pvt. Ltd.                 ...  0.357587  
3   Token Metrics is searching for a highly capabl...  0.356055  
4   Token Metrics is searching for a highly capabl...  0.356055  
..                                                ...       ...  
95  Company Description  Axiado is an AI-enhanced ...  0.237684  
96  Exp: 2 + Years  Location: Gurgaon/ Remote  Ski...  0.237348  
97  Summary                Posted: Dec 7, 2022    ...   0.23677  
98  Summary                Posted: Dec 7, 2022    ...   0.23677  
99  Role Description - (Mumbai Based and Immediate...  0.235978  

[100 rows x 6 columns]

## Combined TFIDF, CV and KNN result together, to make a dataframe "final"


In [262]:
merge1 = knn[['JobID','positionName', 'score']].merge(TF[['JobID','score']], on= "JobID")

In [263]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()a

final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

JobID                    positionName      KNN    TF-IDF        CV
0    91                  Data Scientist  1.25012  0.218604  0.304592
1    95  Data Science - Knowledge Graph  1.25191  0.216358  0.302445
2   779       ASSOCIATE DEVOPS ENGINEER  1.26779   0.19635  0.281624
3   400       MACHINE LEARNING ENGINEER  1.27042  0.193013  0.357587
4   920       MACHINE LEARNING ENGINEER  1.27063  0.192747  0.357587

In [264]:
final

JobID                                       positionName      KNN  \
0     91                                     Data Scientist  1.25012   
1     95                     Data Science - Knowledge Graph  1.25191   
2    779                          ASSOCIATE DEVOPS ENGINEER  1.26779   
3    400                          MACHINE LEARNING ENGINEER  1.27042   
4    920                          MACHINE LEARNING ENGINEER  1.27063   
5     54                          Machine Learning Engineer  1.27347   
6    562                          Machine Learning Engineer  1.27353   
7    183                              Senior Data Scientist   1.2778   
8    334                                     Data Scientist  1.28281   
9    337                                     Data Scientist  1.28323   
10   845                                         AVP-DEVOPS  1.28746   
11    74                      Data Scientist (India Remote)  1.28928   
12   531                      Data Scientist (India Remote)  1.28934   
13   164                        Python Data Science Trainer  1.28984   
14   473                   Python Machine Learning Engineer  1.29281   
15   721                                Automation Engineer  1.29303   
16   711                          Machine Learning Engineer  1.29331   
17   236                          Machine Learning Engineer  1.29333   
18   541                    AI Engineer_MLOPS_3 to 10 years   1.2942   
19  3711                    AI Engineer_MLOPS_3 to 10 years  1.29423   
20   307          Data Science - Lead & Manager/Sr. Manager  1.29578   
21   221                          Machine Learning Engineer  1.29863   
22   713                          Machine Learning Engineer  1.29871   
23   285                                       AI Tech Lead  1.29953   
24   275                 Senior Machine Learning Researcher  1.29981   
25   752                          Machine Learning Engineer  1.30064   
26  1859                          Machine Learning Engineer  1.30068   
27   229                          Machine Learning Engineer  1.30077   
28   444                              Data Science Engineer  1.30083   
29   463                          Machine Learning Engineer  1.30182   
30   140                                     Data Scientist  1.30217   
31   710                          Machine Learning Engineer  1.30374   
32   225                          Machine Learning Engineer  1.30374   
33   284                   Senior Machine Learning Engineer  1.30436   
34   740                   Senior Machine Learning Engineer   1.3045   
35  1970                   Senior Machine Learning Engineer  1.30452   
36   327                                     Data Scientist  1.30656   
37   305                                     Data Scientist  1.30678   
38   450                                 Sr. Data Scientist  1.30678   
39   741      SatSure Analytics - Machine Learning Engineer  1.30743   
40  1999      SatSure Analytics - Machine Learning Engineer  1.30746   
41   296      SatSure Analytics - Machine Learning Engineer  1.30749   
42   294  Senior Machine Learning Engineer Opportunity A...  1.30774   
43   738  Senior Machine Learning Engineer Opportunity A...  1.30776   
44    33                              Data Science Engineer  1.30801   
45   547                              Data Science Engineer  1.30819   
46    78                         Machine Learning Developer  1.30953   
47   199                          Machine Learning Engineer     1.31   
48   714                          Machine Learning Engineer   1.3101   
49   464                            Machine Learning Intern  1.31138   
50   315              Machine Learning Engineer (2-4 years)  1.31386   
51   373                                     AI/ML Engineer  1.31388   
52   871              Machine Learning Engineer (2-4 years)  1.31392   
53   917                                     AI/ML Engineer    1.314   
54   872       Lead Machine Learning Firmwa

In [265]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                                       positionName          KNN  \
0     91                                     Data Scientist     0.333333   
1     95                     Data Science - Knowledge Graph     0.324164   
3    400                          MACHINE LEARNING ENGINEER     0.229635   
4    920                          MACHINE LEARNING ENGINEER     0.228566   
2    779                          ASSOCIATE DEVOPS ENGINEER     0.243061   
11    74                      Data Scientist (India Remote)     0.133341   
12   531                      Data Scientist (India Remote)     0.133032   
14   473                   Python Machine Learning Engineer     0.115319   
8    334                                     Data Scientist      0.16639   
9    337                                     Data Scientist     0.164213   
5     54                          Machine Learning Engineer     0.214047   
6    562                          Machine Learning Engineer     0.213784   
7    183                              Senior Data Scientist     0.191957   
15   721                                Automation Engineer     0.114173   
20   307          Data Science - Lead & Manager/Sr. Manager     0.100118   
10   845                                         AVP-DEVOPS     0.142638   
13   164                        Python Data Science Trainer     0.130479   
24   275                 Senior Machine Learning Researcher    0.0795386   
38   450                                 Sr. Data Scientist    0.0439484   
25   752                          Machine Learning Engineer    0.0753026   
26  1859                          Machine Learning Engineer    0.0751303   
27   229                          Machine Learning Engineer    0.0746498   
18   541                    AI Engineer_MLOPS_3 to 10 years     0.108213   
19  3711                    AI Engineer_MLOPS_3 to 10 years     0.108078   
30   140                                     Data Scientist       0.0675   
49   464                            Machine Learning Intern      0.02047   
23   285                                       AI Tech Lead    0.0809918   
16   711                          Machine Learning Engineer     0.112746   
17   236                          Machine Learning Engineer      0.11263   
33   284                   Senior Machine Learning Engineer    0.0563146   
34   740                   Senior Machine Learning Engineer    0.0556014   
35  1970                   Senior Machine Learning Engineer     0.055508   
21   221                          Machine Learning Engineer    0.0855938   
22   713                          Machine Learning Engineer    0.0851582   
29   463                          Machine Learning Engineer    0.0692753   
39   741      SatSure Analytics - Machine Learning Engineer    0.0406529   
40  1999      SatSure Analytics - Machine Learning Engineer    0.0405042   
41   296      SatSure Analytics - Machine Learning Engineer    0.0403238   
28   444                              Data Science Engineer     0.074335   
37   305                                     Data Scientist     0.043983   
44    33                              Data Science Engineer    0.0376756   
45   547                              Data Science Engineer    0.0367416   
42   294  Senior Machine Learning Engineer Opportunity A...    0.0390448   
43   738  Senior Machine Learning Engineer Opportunity A...    0.0389546   
50   315              Machine Learning Engineer (2-4 years)   0.00783276   
52   871              Machine Learning Engineer (2-4 years)   0.00748792   
46    78                         Machine Learning Developer    0.0299081   
31   710                          Machine Learning Engineer    0.0594978   
32   225                          Machine Learning Engineer    0.0594786   
36   327                                     Data Scientist    0.0450652   
47   199                          Machine Learning Engineer    0.0275196   
48   714                          Machine Learning 

In [266]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

JobID                                       positionName          KNN  \
0     91                                     Data Scientist     0.333333   
1     95                     Data Science - Knowledge Graph     0.324164   
3    400                          MACHINE LEARNING ENGINEER     0.229635   
4    920                          MACHINE LEARNING ENGINEER     0.228566   
2    779                          ASSOCIATE DEVOPS ENGINEER     0.243061   
11    74                      Data Scientist (India Remote)     0.133341   
12   531                      Data Scientist (India Remote)     0.133032   
14   473                   Python Machine Learning Engineer     0.115319   
8    334                                     Data Scientist      0.16639   
9    337                                     Data Scientist     0.164213   
5     54                          Machine Learning Engineer     0.214047   
6    562                          Machine Learning Engineer     0.213784   
7    183                              Senior Data Scientist     0.191957   
15   721                                Automation Engineer     0.114173   
20   307          Data Science - Lead & Manager/Sr. Manager     0.100118   
10   845                                         AVP-DEVOPS     0.142638   
13   164                        Python Data Science Trainer     0.130479   
24   275                 Senior Machine Learning Researcher    0.0795386   
38   450                                 Sr. Data Scientist    0.0439484   
25   752                          Machine Learning Engineer    0.0753026   
26  1859                          Machine Learning Engineer    0.0751303   
27   229                          Machine Learning Engineer    0.0746498   
18   541                    AI Engineer_MLOPS_3 to 10 years     0.108213   
19  3711                    AI Engineer_MLOPS_3 to 10 years     0.108078   
30   140                                     Data Scientist       0.0675   
49   464                            Machine Learning Intern      0.02047   
23   285                                       AI Tech Lead    0.0809918   
16   711                          Machine Learning Engineer     0.112746   
17   236                          Machine Learning Engineer      0.11263   
33   284                   Senior Machine Learning Engineer    0.0563146   
34   740                   Senior Machine Learning Engineer    0.0556014   
35  1970                   Senior Machine Learning Engineer     0.055508   
21   221                          Machine Learning Engineer    0.0855938   
22   713                          Machine Learning Engineer    0.0851582   
29   463                          Machine Learning Engineer    0.0692753   
39   741      SatSure Analytics - Machine Learning Engineer    0.0406529   
40  1999      SatSure Analytics - Machine Learning Engineer    0.0405042   
41   296      SatSure Analytics - Machine Learning Engineer    0.0403238   
28   444                              Data Science Engineer     0.074335   
37   305                                     Data Scientist     0.043983   
44    33                              Data Science Engineer    0.0376756   
45   547                              Data Science Engineer    0.0367416   
42   294  Senior Machine Learning Engineer Opportunity A...    0.0390448   
43   738  Senior Machine Learning Engineer Opportunity A...    0.0389546   
50   315              Machine Learning Engineer (2-4 years)   0.00783276   
52   871              Machine Learning Engineer (2-4 years)   0.00748792   
46    78                         Machine Learning Developer    0.0299081   
31   710                          Machine Learning Engineer    0.0594978   
32   225                          Machine Learning Engineer    0.0594786   
36   327                                     Data Scientist    0.0450652   
47   199                          Machine Learning Engineer    0.0275196   
48   714                          Machine Learning 

In [267]:
# final2.merge(df, on="JobID")
final_df = df.merge(final2, on="JobID")
final_df

id                                            company  \
0   1336f2ba99b7aa51                                            Emerson   
1   d6a9445dca6529ca                                    Revolo InfoTech   
2   8099c00f755726f3                                      Token Metrics   
3   23291deee438b2dc                  Analog and Digital Labs India Pvt   
4   a388c042d99345d2                            Chubb INA Holdings Inc.   
5   5f449b74d67e072d                            Chubb INA Holdings Inc.   
6   7abc93fb606577de                   Pridetech labs pvt ltd Bangalore   
7   0411db7f75aa4a13                         Payas Technologies Pvt Ltd   
8   c12e50690eed7838                                    Simplifai India   
9   464f8855716a27dc                              CogniveAI Innovations   
10  2a9f5be670fb65c7                                          Brightree   
11  8105213e81e590ac                                              Apple   
12  292982d45a49af6a                            SatSure Analytics India   
13  ffab9b464de14332                                            Corteva   
14  962f30f070aa901c                            SatSure Analytics India   
15  0d223e0f20aa223a                            SatSure Analytics India   
16  d5e6985332347fe1                                             GoPrac   
17  ae53b42a89a73ba0                                     Wolters Kluwer   
18  cfd02e7f11f0f60e                                         ConsultBae   
19  bc68d63c44c5878f             Radome Technologies & Services Pvt Ltd   
20  1b59fe7b8b0272e7                               SA Technologies Inc.   
21  fa7188929e29072e                      Digispoc Technology Pvt. Ltd.   
22  8f92f1d5834d4f5b                       Ergode IT Services Pvt. ltd.   
23  b0d424bf8f41e756                                          Capgemini   
24  48627303be6e24fb                                   Capgemini Invent   
25  86b7ee059bfbd90d                                             Axiado   
26  06dc76b1654530f6                                          BizAcuity   
27  4d15f9d4352f1957                                Amanzi Technologies   
28  5766ffdb7210ff84                             F(x) Data Labs PVT LTD   
29  561c23c0a50ac32c                                Insourcedev Pvt Ltd   
30  3e0bf3dda3f603ee                                         WELD GROUP   
31  adad0eca2919bb70                                         Feynn Labs   
32  28d3c0788d6dc58d                             Vingsfire HRIM Pvt Ltd   
33  8099c00f755726f3                                      Token Metrics   
34  ef735b0ff2f73b06                                  Fractal Analytics   
35  1336f2ba99b7aa51                                            Emerson   
36  d6a9445dca6529ca                                    Revolo InfoTech   
37  8105213e81e590ac                                              Apple   
38  ffab9b464de14332                                            Corteva   
39  2a9f5be670fb65c7                                          Brightree   
40  464f8855716a27dc                              CogniveAI Innovations   
41  2bfabb73036c97c8  Mercedes-Benz Research and Development India P...   
42  ae53b42a89a73ba0                                     Wolters Kluwer   
43  0d223e0f20aa223a                            SatSure Analytics India   
44  cfd02e7f11f0f60e                                         ConsultBae   
45  292982d45a49af6a                            SatSure Analytics India   
46  1eb3a819c39dc74c                                    SKS Enterpprise   
47  fb0fcc2a339e1819                                    SKS Enterpprise   
48  fa7188929e29072e                      Digispoc Technology Pvt. Ltd.   
49  86b7ee059bfbd90d                                             Axiado   
50  06dc76b1654530f6                                          BizAcuity   
51  4d15f9d4352f1957                                Amanzi Technologies   
52  292982d45a49af6a                       

In [269]:
final_df.to_csv("final_df.csv",index=False)
