In [1]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [3]:
# Import CV
f=open('textfile.txt','r', errors = 'ignore')
text=f.read()

In [8]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’'))
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [9]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [10]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['rakshit',
 'khajuriamachine',
 'learning',
 'engineertalab',
 'tillo',
 'gole',
 'gujral',
 '180002',
 'jammu',
 'india',
 'rakshitraina1234',
 'gmail.com',
 '914955615514',
 'aug',
 '2001',
 'http',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/',
 'http',
 '//github.com/ryzxxl9149556155summaryskilled',
 'developing',
 'implementing',
 'data-driven',
 'solution',
 'real-world',
 'problem',
 'utilizing',
 'range',
 'tool',
 'andtechniques',
 'extract',
 'valuable',
 'insight',
 'large',
 'complex',
 'data',
 'set',
 'posse',
 'diverse',
 'experience',
 'cleaningand',
 'analyzing',
 'data',
 'enhancing',
 'existing',
 'model',
 'continuously',
 'seeking',
 'enhance',
 'skill',
 'broaden',
 'myknowledge',
 'dynamic',
 '\x00eld',
 'data',
 'science.skillstools',
 'python',
 'git',
 'github',
 'jupyter',
 'notebook',
 'anaconda',
 'v',
 'codepackages',
 'scikit-learn',
 'numpy',
 'panda',
 'matplotlib',
 'nltk',
 'tensorflow',
 'flask',
 'streamlit',
 'spacy',
 'text',
 'blob',
 'va

In [11]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(('\x00eld', 'data'), 2)
(('\x00ne-tuning', 'pre-trained'), 2)
(('.', 'transformer'), 2)
(('.improved', 'model'), 2)
(('//github.com/ryzxxl9149556155summaryskilled', 'developing'), 2)
(('//www.linkedin.com/in/rakshit-khajuria-3627781b8/', 'http'), 2)
(('180002', 'jammu'), 2)
(('2001', 'http'), 2)
(('2020', 'aug'), 2)
(('2021became', 'pro\x00cient'), 2)
(('2022', 'presentjammu'), 2)
(('914955615514', 'aug'), 2)
(('accuracy', 'applying'), 2)
(('accurately', 'analyze'), 2)
(('advanced', 'technique'), 2)
(('algorithm', 'decision'), 2)
(('algorithm', 'e.g'), 2)
(('algorithm', 'including'), 2)
(('anaconda', 'v'), 2)
(('analysis', 'model'), 2)
(('analysis', 'text'), 2)
(('analyze', 'andinterpret'), 2)
(('analyzing', 'data'), 2)
(('andinterpret', 'sentiment.enhanced'), 2)
(('andtechniques', 'extract'), 2)
(('applying', 'different'), 2)
(('aslstm', 'bilstm'), 2)
(('aug', '2001'), 2)
(('aug', '2021became'), 2)
(('aws', 'ef\x00ciently'), 2)
(('bangalore', 'indiaunderlying'), 2)
(('bert', 'lstms')

['\x00eld data',
 '\x00ne-tuning pre-trained',
 '. transformer',
 '.improved model',
 '//github.com/ryzxxl9149556155summaryskilled developing',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/ http',
 '180002 jammu',
 '2001 http',
 '2020 aug',
 '2021became pro\x00cient',
 '2022 presentjammu',
 '914955615514 aug',
 'accuracy applying',
 'accurately analyze',
 'advanced technique',
 'algorithm decision',
 'algorithm e.g',
 'algorithm including',
 'anaconda v',
 'analysis model',
 'analysis text',
 'analyze andinterpret',
 'analyzing data',
 'andinterpret sentiment.enhanced',
 'andtechniques extract',
 'applying different',
 'aslstm bilstm',
 'aug 2001',
 'aug 2021became',
 'aws ef\x00ciently',
 'bangalore indiaunderlying',
 'bert lstms',
 'bert models.machine',
 'bilstm etc',
 'blob vader.machine',
 'broaden myknowledge',
 'classi\x00cation named',
 'classifyemotional context',
 'cleaningand analyzing',
 'cloud platform',
 'clustering algorithm',
 'codepackages scikit-learn',
 'comple

# Importing scapped df

In [25]:
DF_PATH = "data.csv"

In [26]:
df = pd.read_csv(DF_PATH)
df

company  \
0                                        Rambøll   
1                                           AT&T   
2                      JPMorgan Chase Bank, N.A.   
3                            Moody's Corporation   
4                      JPMorgan Chase Bank, N.A.   
...                                          ...   
5497                                      Emurgo   
5498  App Incubator Technologies Private Limited   
5499                                       ZigUp   
5500                         DIFX Technology LLC   
5501                      Parsh Technologies LLP   

                              positionName  \
0          Associate Analyst - ERP Support   
1     TECH SPECIALIST, SECURITY COMPLIANCE   
2                     Indirect Tax Analyst   
3           Financial Data Associate - MSC   
4                  Quant Analytics Analyst   
...                                    ...   
5497                  Front End Developers   
5498             iOS Application Developer   
5499  Senior Software Engineer (Wordpress)   
5500                           QA Engineer   
5501                  Blockchain Developer   

                                            description  \
0     \n\n \n  \n   Company Description\n  \n  \n   ...   
1     Security and compliance analyst that supports ...   
2     \n Primary Responsibilities: \n \n \n  Run mul...   
3     \n \n  \n   \n    \n     As a Financial Data A...   
4     \n Description for Internal & External Candida...   
...                                                 ...   
5497  \n **We are hiring for Front End Mid-Level and...   
5498  AppIncubator Technologies  - is an award-winni...   
5499  \n\n PlotX New Delhi | 4~8y \n \n  \n   Full S...   
5500  Job Opportunity – QA Engineer\nDIFX\nDIFX is t...   
5501  We are looking for a highly capable blockchain...   

                             salary              location  rating  \
0                               NaN      Gurgaon, Haryana     3.9   
1                               NaN  Hyderabad, Telangana     3.7   
2                               NaN   Mumbai, Maharashtra     3.9   
3                               NaN      Gurgaon, Haryana     3.6   
4                               NaN  Bengaluru, Karnataka     3.9   
...                             ...                   ...     ...   
5497                            NaN  Bengaluru, Karnataka     NaN   
5498  ₹5,00,000 - ₹15,00,000 a year  Hyderabad, Telangana     NaN   
5499                            NaN      New Delhi, Delhi     NaN   
5500                            NaN  Bengaluru, Karnataka     NaN   
5501      ₹30,000 - ₹50,000 a month       Rajkot, Gujarat     NaN   

      reviewsCount      postedAt  \
0            211.0   Just posted   
1          43942.0         Today   
2          18023.0         Today   
3            505.0         Today   
4          18023.0         Today   
...            ...           ...   
5497           NaN  30+ days ago   
5498           NaN  30+ days ago   
5499           NaN  30+ days ago   
5500           NaN  30+ days ago   
5501           NaN  30+ days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=cc96b53863...   
1     https://in.indeed.com/applystart?jk=5922b50e70...   
2     https://in.indeed.com/applystart?jk=fdcc6c2892...   
3     https://in.indeed.com/applystart?jk=21d74dd3fd...   
4     https://in.indeed.com/applystart?jk=0236f8792c...   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499  https://in.indeed.com/applystart?jk=05a01b83b3...   
5500                                                NaN   
5501                                                NaN   

                                                    url  
0     https://www.indeed.co.in/rc/clk?jk=cc96b538634...  
1     https://www.indeed.co.in/rc/clk?jk=5922b50e707...  
2     htt

In [27]:
df.shape


(5502, 10)

In [28]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   company            5408 non-null   object 
 1   positionName       5502 non-null   object 
 2   description        5502 non-null   object 
 3   salary             1248 non-null   object 
 4   location           5502 non-null   object 
 5   rating             3128 non-null   float64
 6   reviewsCount       3128 non-null   float64
 7   postedAt           5502 non-null   object 
 8   externalApplyLink  4044 non-null   object 
 9   url                5502 non-null   object 
dtypes: float64(2), object(8)
memory usage: 430.0+ KB


In [29]:
df['All'] = df[df.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)

In [30]:
df

company  \
0                                        Rambøll   
1                                           AT&T   
2                      JPMorgan Chase Bank, N.A.   
3                            Moody's Corporation   
4                      JPMorgan Chase Bank, N.A.   
...                                          ...   
5497                                      Emurgo   
5498  App Incubator Technologies Private Limited   
5499                                       ZigUp   
5500                         DIFX Technology LLC   
5501                      Parsh Technologies LLP   

                              positionName  \
0          Associate Analyst - ERP Support   
1     TECH SPECIALIST, SECURITY COMPLIANCE   
2                     Indirect Tax Analyst   
3           Financial Data Associate - MSC   
4                  Quant Analytics Analyst   
...                                    ...   
5497                  Front End Developers   
5498             iOS Application Developer   
5499  Senior Software Engineer (Wordpress)   
5500                           QA Engineer   
5501                  Blockchain Developer   

                                            description  \
0     \n\n \n  \n   Company Description\n  \n  \n   ...   
1     Security and compliance analyst that supports ...   
2     \n Primary Responsibilities: \n \n \n  Run mul...   
3     \n \n  \n   \n    \n     As a Financial Data A...   
4     \n Description for Internal & External Candida...   
...                                                 ...   
5497  \n **We are hiring for Front End Mid-Level and...   
5498  AppIncubator Technologies  - is an award-winni...   
5499  \n\n PlotX New Delhi | 4~8y \n \n  \n   Full S...   
5500  Job Opportunity – QA Engineer\nDIFX\nDIFX is t...   
5501  We are looking for a highly capable blockchain...   

                             salary              location  rating  \
0                               NaN      Gurgaon, Haryana     3.9   
1                               NaN  Hyderabad, Telangana     3.7   
2                               NaN   Mumbai, Maharashtra     3.9   
3                               NaN      Gurgaon, Haryana     3.6   
4                               NaN  Bengaluru, Karnataka     3.9   
...                             ...                   ...     ...   
5497                            NaN  Bengaluru, Karnataka     NaN   
5498  ₹5,00,000 - ₹15,00,000 a year  Hyderabad, Telangana     NaN   
5499                            NaN      New Delhi, Delhi     NaN   
5500                            NaN  Bengaluru, Karnataka     NaN   
5501      ₹30,000 - ₹50,000 a month       Rajkot, Gujarat     NaN   

      reviewsCount      postedAt  \
0            211.0   Just posted   
1          43942.0         Today   
2          18023.0         Today   
3            505.0         Today   
4          18023.0         Today   
...            ...           ...   
5497           NaN  30+ days ago   
5498           NaN  30+ days ago   
5499           NaN  30+ days ago   
5500           NaN  30+ days ago   
5501           NaN  30+ days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=cc96b53863...   
1     https://in.indeed.com/applystart?jk=5922b50e70...   
2     https://in.indeed.com/applystart?jk=fdcc6c2892...   
3     https://in.indeed.com/applystart?jk=21d74dd3fd...   
4     https://in.indeed.com/applystart?jk=0236f8792c...   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499  https://in.indeed.com/applystart?jk=05a01b83b3...   
5500                                                NaN   
5501                                                NaN   

                                                    url  \
0     https://www.indeed.co.in/rc/clk?jk=cc96b538634...   
1     https://www.indeed.co.in/rc/clk?jk=5922b50e707...   
2     

In [31]:
df['All']

0       Rambøll,Associate Analyst - ERP Support,\n\n \...
1       AT&T,TECH SPECIALIST, SECURITY COMPLIANCE,Secu...
2       JPMorgan Chase Bank, N.A.,Indirect Tax Analyst...
3       Moody's Corporation,Financial Data Associate -...
4       JPMorgan Chase Bank, N.A.,Quant Analytics Anal...
                              ...                        
5497    Emurgo,Front End Developers,\n **We are hiring...
5498    App Incubator Technologies Private Limited,iOS...
5499    ZigUp,Senior Software Engineer (Wordpress),\n\...
5500    DIFX Technology LLC,QA Engineer,Job Opportunit...
5501    Parsh Technologies LLP,Blockchain Developer,We...
Name: All, Length: 5502, dtype: object

In [72]:
df = df.replace(r'\n','', regex=True) 
df = df.replace(' ', '')
df.description = df.description.str.strip()
df.All = df.All.str.strip()

In [75]:
df

company  \
0                                        Rambøll   
1                                           AT&T   
2                      JPMorgan Chase Bank, N.A.   
3                            Moody's Corporation   
4                      JPMorgan Chase Bank, N.A.   
...                                          ...   
5497                                      Emurgo   
5498  App Incubator Technologies Private Limited   
5499                                       ZigUp   
5500                         DIFX Technology LLC   
5501                      Parsh Technologies LLP   

                              positionName  \
0          Associate Analyst - ERP Support   
1     TECH SPECIALIST, SECURITY COMPLIANCE   
2                     Indirect Tax Analyst   
3           Financial Data Associate - MSC   
4                  Quant Analytics Analyst   
...                                    ...   
5497                  Front End Developers   
5498             iOS Application Developer   
5499  Senior Software Engineer (Wordpress)   
5500                           QA Engineer   
5501                  Blockchain Developer   

                                            description  \
0     Company Description        Ramboll has more th...   
1     Security and compliance analyst that supports ...   
2     Primary Responsibilities:     Run multiple rep...   
3     As a Financial Data Associate, you will work i...   
4     Description for Internal & External Candidates...   
...                                                 ...   
5497  **We are hiring for Front End Mid-Level and Le...   
5498  AppIncubator Technologies  - is an award-winni...   
5499  PlotX New Delhi | 4~8y       Full Stack       ...   
5500  Job Opportunity – QA EngineerDIFXDIFX is the w...   
5501  We are looking for a highly capable blockchain...   

                             salary              location  rating  \
0                               NaN      Gurgaon, Haryana     3.9   
1                               NaN  Hyderabad, Telangana     3.7   
2                               NaN   Mumbai, Maharashtra     3.9   
3                               NaN      Gurgaon, Haryana     3.6   
4                               NaN  Bengaluru, Karnataka     3.9   
...                             ...                   ...     ...   
5497                            NaN  Bengaluru, Karnataka     NaN   
5498  ₹5,00,000 - ₹15,00,000 a year  Hyderabad, Telangana     NaN   
5499                            NaN      New Delhi, Delhi     NaN   
5500                            NaN  Bengaluru, Karnataka     NaN   
5501      ₹30,000 - ₹50,000 a month       Rajkot, Gujarat     NaN   

      reviewsCount      postedAt  \
0            211.0   Just posted   
1          43942.0         Today   
2          18023.0         Today   
3            505.0         Today   
4          18023.0         Today   
...            ...           ...   
5497           NaN  30+ days ago   
5498           NaN  30+ days ago   
5499           NaN  30+ days ago   
5500           NaN  30+ days ago   
5501           NaN  30+ days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=cc96b53863...   
1     https://in.indeed.com/applystart?jk=5922b50e70...   
2     https://in.indeed.com/applystart?jk=fdcc6c2892...   
3     https://in.indeed.com/applystart?jk=21d74dd3fd...   
4     https://in.indeed.com/applystart?jk=0236f8792c...   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499  https://in.indeed.com/applystart?jk=05a01b83b3...   
5500                                                NaN   
5501                                                NaN   

                                                    url  \
0     https://www.indeed.co.in/rc/clk?jk=cc96b538634...   
1     https://www.indeed.co.in/rc/clk?jk=5922b50e707...   
2     

# Put keywords of the CV into a dataframe

In [76]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

In [77]:
df2

title job highlights job description company overview industry  \
0     I              I               I                I        I   

                                                 All  
0  eld data ne-tuning pre-trained . transformer...

In [78]:
df.columns

Index(['company', 'positionName', 'description', 'salary', 'location',
       'rating', 'reviewsCount', 'postedAt', 'externalApplyLink', 'url',
       'All'],
      dtype='object')

# Recomendation Function

#klnsdsd

In [79]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['positionName', 'company',"location", 'rating' 'description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        
        recommendation.at[count, 'positionName'] = df['positionName'][i]
        recommendation.at[count, 'company'] = df['company'][i]
        recommendation.at[count, 'location'] = df['location'][i]
        recommendation.at[count, 'rating'] = df['rating'][i]
        recommendation.at[count, 'description'] = df['description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

In [80]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])

In [81]:
output2

[array([[0.02514581]]),
 array([[0.02499205]]),
 array([[0.02500962]]),
 array([[0.0310437]]),
 array([[0.03355642]]),
 array([[0.0962123]]),
 array([[0.01743493]]),
 array([[0.03305435]]),
 array([[0.04056072]]),
 array([[0.0316218]]),
 array([[0.01100881]]),
 array([[0.03062406]]),
 array([[0.02879082]]),
 array([[0.05634831]]),
 array([[0.03093038]]),
 array([[0.03119468]]),
 array([[0.06054285]]),
 array([[0.03905109]]),
 array([[0.07699498]]),
 array([[0.0266674]]),
 array([[0.02688439]]),
 array([[0.01767505]]),
 array([[0.03166086]]),
 array([[0.0347697]]),
 array([[0.03173996]]),
 array([[0.03885379]]),
 array([[0.01767192]]),
 array([[0.02104544]]),
 array([[0.0279169]]),
 array([[0.04800697]]),
 array([[0.03339547]]),
 array([[0.02581638]]),
 array([[0.02774557]]),
 array([[0.04270864]]),
 array([[0.01939521]]),
 array([[0.10005561]]),
 array([[0.03673633]]),
 array([[0.02822499]]),
 array([[0.00651427]]),
 array([[0.02318502]]),
 array([[0.03626335]]),
 array([[0.03161337]])

In [82]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All']) #fitting and transforming the vector
count_jobid

<5502x49440 sparse matrix of type '<class 'numpy.int64'>'
	with 1650467 stored elements in Compressed Sparse Row format>

In [83]:
# print(count_jobid)


In [84]:
user_count = count_vectorizer.transform(df2['All'])
user_count

<1x49440 sparse matrix of type '<class 'numpy.int64'>'
	with 153 stored elements in Compressed Sparse Row format>

In [85]:
print(user_count)

  (0, 2301)	2
  (0, 2355)	2
  (0, 2358)	2
  (0, 12685)	2
  (0, 12687)	2
  (0, 13040)	2
  (0, 13460)	5
  (0, 13689)	2
  (0, 13700)	3
  (0, 13739)	2
  (0, 13744)	2
  (0, 13817)	2
  (0, 14080)	2
  (0, 14683)	4
  (0, 14858)	2
  (0, 15490)	2
  (0, 15931)	4
  (0, 16229)	2
  (0, 19801)	2
  (0, 21803)	2
  (0, 21855)	3
  (0, 22099)	8
  (0, 22315)	2
  (0, 22414)	2
  (0, 22704)	2
  :	:
  (0, 44882)	4
  (0, 45151)	2
  (0, 45704)	2
  (0, 45744)	4
  (0, 45929)	2
  (0, 46025)	4
  (0, 46026)	2
  (0, 46403)	2
  (0, 46436)	1
  (0, 46466)	2
  (0, 46497)	2
  (0, 46625)	4
  (0, 46670)	2
  (0, 46753)	2
  (0, 46911)	2
  (0, 47349)	4
  (0, 47463)	2
  (0, 47484)	3
  (0, 47514)	2
  (0, 47516)	2
  (0, 47609)	2
  (0, 48557)	2
  (0, 48709)	4
  (0, 48793)	2
  (0, 48885)	2


In [86]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
#output3

In [87]:
output3

[array([[0.08271119]]),
 array([[0.10474688]]),
 array([[0.09482028]]),
 array([[0.10372172]]),
 array([[0.09783041]]),
 array([[0.18869465]]),
 array([[0.071908]]),
 array([[0.07243559]]),
 array([[0.12712436]]),
 array([[0.09186617]]),
 array([[0.05881143]]),
 array([[0.09186005]]),
 array([[0.07384546]]),
 array([[0.10853658]]),
 array([[0.0739589]]),
 array([[0.08130643]]),
 array([[0.1874395]]),
 array([[0.09807573]]),
 array([[0.20438331]]),
 array([[0.06336599]]),
 array([[0.09557771]]),
 array([[0.08841008]]),
 array([[0.0962981]]),
 array([[0.07025144]]),
 array([[0.07744288]]),
 array([[0.09484655]]),
 array([[0.05825042]]),
 array([[0.0735303]]),
 array([[0.08867963]]),
 array([[0.11213047]]),
 array([[0.08981903]]),
 array([[0.05987752]]),
 array([[0.08147986]]),
 array([[0.10329604]]),
 array([[0.06910303]]),
 array([[0.15773034]]),
 array([[0.09526771]]),
 array([[0.0718194]]),
 array([[0.05071934]]),
 array([[0.06632803]]),
 array([[0.11721705]]),
 array([[0.07980482]]),

In [88]:
df.rating

0       3.9
1       3.7
2       3.9
3       3.6
4       3.9
       ... 
5497    NaN
5498    NaN
5499    NaN
5500    NaN
5501    NaN
Name: rating, Length: 5502, dtype: float64

In [89]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

positionName  \
0                      MACHINE LEARNING ENGINEER   
1                      MACHINE LEARNING ENGINEER   
2                  Data Scientist (India Remote)   
3                  Data Scientist (India Remote)   
4               Python Machine Learning Engineer   
..                                           ...   
95  Lead Machine Learning Firmware Test Engineer   
96  Lead Machine Learning Firmware Test Engineer   
97                     Machine Learning Engineer   
98                     Machine Learning Engineer   
99                                   ML Engineer   

                          company              location ratingdescription  \
0             Amanzi Technologies  Noida, Uttar Pradesh               NaN   
1             Amanzi Technologies  Noida, Uttar Pradesh               NaN   
2                   Token Metrics  Bengaluru, Karnataka               NaN   
3                   Token Metrics  Bengaluru, Karnataka               NaN   
4          Vingsfire HRIM Pvt Ltd   Madurai, Tamil Nadu               NaN   
..                            ...                   ...               ...   
95                         Axiado  Hyderabad, Telangana               NaN   
96                         Axiado  Hyderabad, Telangana               NaN   
97                          Apple  Bengaluru, Karnataka               NaN   
98                          Apple  Bengaluru, Karnataka               NaN   
99  krtrimaIQ Cognitive Solutions  Bengaluru, Karnataka               NaN   

       score  rating                                        description  
0   0.358269     NaN  Amanzi Technologies Pvt. Ltd.                 ...  
1   0.358269     NaN  Amanzi Technologies Pvt. Ltd.                 ...  
2   0.356535     NaN  Token Metrics is searching for a highly capabl...  
3   0.356535     NaN  Token Metrics is searching for a highly capabl...  
4   0.354861     NaN  Role : Senior Python DeveloperExperience: 5+ Y...  
..       ...     ...                                                ...  
95  0.237843     NaN  Company Description  Axiado is an AI-enhanced ...  
96  0.237843     NaN  Company Description  Axiado is an AI-enhanced ...  
97  0.236957     4.1  Summary                Posted: Dec 7, 2022    ...  
98  0.236957     4.1  Summary                Posted: Dec 7, 2022    ...  
99  0.236566     NaN  Job Description:ML Engineer for NLP domain.Res...  

[100 rows x 7 columns]

In [90]:
cv.description[1]

'Amanzi Technologies Pvt. Ltd.                              Permanent                              Noida                              Posted 3 weeks ago                          Out of the box solution          Responsibilities:      Designing and developing machine learning and deep learning systems.    Running machine learning tests and experiments.    Implementing appropriate ML algorithms.        Job brief:   We are looking for a Machine Learning (ML) Engineer to help us create artificial intelligence products.   Machine Learning Engineer responsibilities include creating machine learning models and retraining systems. To do this job successfully, you need exceptional skills in statistics and programming. If you also have knowledge of data science and software engineering, we’d like to meet you.   Your ultimate goal will be to shape and build efficient self-learning applications.   Responsibilities:      Study and transform data science prototypes.    Design machine learning system

In [101]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    n_neighbors = 100
    KNN = NearestNeighbors(n_neighbors, p=2)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given