In [132]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [133]:
# Import CV
f=open('textfile.txt','r', errors = 'ignore')
text=f.read()

In [134]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’'))
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [135]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [136]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['rakshit',
 'khajuriamachine',
 'learning',
 'engineertalab',
 'tillo',
 'gole',
 'gujral',
 '180002',
 'jammu',
 'india',
 'rakshitraina1234',
 'gmail.com',
 '914955615514',
 'aug',
 '2001',
 'http',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/',
 'http',
 '//github.com/ryzxxl9149556155summaryskilled',
 'developing',
 'implementing',
 'data-driven',
 'solution',
 'real-world',
 'problem',
 'utilizing',
 'range',
 'tool',
 'andtechniques',
 'extract',
 'valuable',
 'insight',
 'large',
 'complex',
 'data',
 'set',
 'posse',
 'diverse',
 'experience',
 'cleaningand',
 'analyzing',
 'data',
 'enhancing',
 'existing',
 'model',
 'continuously',
 'seeking',
 'enhance',
 'skill',
 'broaden',
 'myknowledge',
 'dynamic',
 '\x00eld',
 'data',
 'science.skillstools',
 'python',
 'git',
 'github',
 'jupyter',
 'notebook',
 'anaconda',
 'v',
 'codepackages',
 'scikit-learn',
 'numpy',
 'panda',
 'matplotlib',
 'nltk',
 'tensorflow',
 'flask',
 'streamlit',
 'spacy',
 'text',
 'blob',
 'va

In [137]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(('\x00eld', 'data'), 2)
(('\x00ne-tuning', 'pre-trained'), 2)
(('.', 'transformer'), 2)
(('.improved', 'model'), 2)
(('//github.com/ryzxxl9149556155summaryskilled', 'developing'), 2)
(('//www.linkedin.com/in/rakshit-khajuria-3627781b8/', 'http'), 2)
(('180002', 'jammu'), 2)
(('2001', 'http'), 2)
(('2020', 'aug'), 2)
(('2021became', 'pro\x00cient'), 2)
(('2022', 'presentjammu'), 2)
(('914955615514', 'aug'), 2)
(('accuracy', 'applying'), 2)
(('accurately', 'analyze'), 2)
(('advanced', 'technique'), 2)
(('algorithm', 'decision'), 2)
(('algorithm', 'e.g'), 2)
(('algorithm', 'including'), 2)
(('anaconda', 'v'), 2)
(('analysis', 'model'), 2)
(('analysis', 'text'), 2)
(('analyze', 'andinterpret'), 2)
(('analyzing', 'data'), 2)
(('andinterpret', 'sentiment.enhanced'), 2)
(('andtechniques', 'extract'), 2)
(('applying', 'different'), 2)
(('aslstm', 'bilstm'), 2)
(('aug', '2001'), 2)
(('aug', '2021became'), 2)
(('aws', 'ef\x00ciently'), 2)
(('bangalore', 'indiaunderlying'), 2)
(('bert', 'lstms')

['\x00eld data',
 '\x00ne-tuning pre-trained',
 '. transformer',
 '.improved model',
 '//github.com/ryzxxl9149556155summaryskilled developing',
 '//www.linkedin.com/in/rakshit-khajuria-3627781b8/ http',
 '180002 jammu',
 '2001 http',
 '2020 aug',
 '2021became pro\x00cient',
 '2022 presentjammu',
 '914955615514 aug',
 'accuracy applying',
 'accurately analyze',
 'advanced technique',
 'algorithm decision',
 'algorithm e.g',
 'algorithm including',
 'anaconda v',
 'analysis model',
 'analysis text',
 'analyze andinterpret',
 'analyzing data',
 'andinterpret sentiment.enhanced',
 'andtechniques extract',
 'applying different',
 'aslstm bilstm',
 'aug 2001',
 'aug 2021became',
 'aws ef\x00ciently',
 'bangalore indiaunderlying',
 'bert lstms',
 'bert models.machine',
 'bilstm etc',
 'blob vader.machine',
 'broaden myknowledge',
 'classi\x00cation named',
 'classifyemotional context',
 'cleaningand analyzing',
 'cloud platform',
 'clustering algorithm',
 'codepackages scikit-learn',
 'comple

# Importing scapped df

In [138]:
DF_PATH = "data.csv"

In [139]:
df = pd.read_csv(DF_PATH)
df

id                                         company  \
0     2567a216d4af7021                                            AT&T   
1     442ad7cc38a6f7b8                           ICICI Prudential Life   
2     e0fe53f38f84e7bd                           ICICI Prudential Life   
3     363b96425a82d12d                                    TMI Group IN   
4     215ece39050fb3f5                   Shairu Gems Diamonds PVT.LTD.   
...                ...                                             ...   
5497  f53ad1277acdc74c                                   VISION ESTEEM   
5498  2b1b759b9c3a9246                                 L.R. Patel & Co   
5499  745a1ac63a001f46                Proactive Consultants & Services   
5500  d7901b874316b5d7  American Academy of Financial Management India   
5501  837f8b5ef252bcd0                          SV Placement Solutions   

                     positionName  \
0      SPECIALIST, DATA ANALYTICS   
1                  Data scientist   
2           Data scientist - Lead   
3                 Bot NLP Analyst   
4           Senior Data Scientist   
...                           ...   
5497           Executive HR Admin   
5498                 HR Recruiter   
5499                 HR Recruiter   
5500        Recruitment Executive   
5501  HR Recruiter (females only)   

                                            description  \
0     \n \n  Experienced data analyst position that ...   
1     Roles and responsibilities:\n 1. Data processi...   
2     Roles and responsibilities:\n 1. Data processi...   
3     \n Job Information \n \n \n  \n   \n    Salary...   
4     Sr. Data Analyst,\nShairu Gems Diamonds PVT. L...   
...                                                 ...   
5497  Urgently looking Executive HR and Admin for le...   
5498  JOB OVERVIEW: The HR Assistant duties involve ...   
5499  Dear candidates,\nWe have an urgent Opening fo...   
5500  Roles & Responsibilities :\nDesign and update ...   
5501  \n Partnering with hiring managers to determin...   

                              salary                location  rating  \
0                                NaN    Hyderabad, Telangana     3.7   
1                                NaN     Mumbai, Maharashtra     4.0   
2                                NaN     Mumbai, Maharashtra     4.0   
3     ₹10,00,000 - ₹16,00,000 a year    Hyderabad, Telangana     NaN   
4          ₹25,000 - ₹35,000 a month          Surat, Gujarat     NaN   
...                              ...                     ...     ...   
5497       ₹20,000 - ₹25,000 a month  Chandigarh, Chandigarh     NaN   
5498       ₹15,000 - ₹20,000 a month      Ahmedabad, Gujarat     NaN   
5499       ₹20,000 - ₹25,000 a month        New Delhi, Delhi     NaN   
5500       ₹20,000 - ₹25,000 a month            Delhi, Delhi     NaN   
5501        ₹8,000 - ₹12,000 a month         Patiala, Punjab     5.0   

      reviewsCount     postedAt  \
0          43942.0        Today   
1           1391.0  Just posted   
2           1391.0  Just posted   
3              NaN    1 day ago   
4              NaN        Today   
...            ...          ...   
5497           NaN   2 days ago   
5498           NaN   2 days ago   
5499           NaN   2 days ago   
5500           NaN   2 days ago   
5501           2.0   2 days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=2567a216d4...   
1     https://in.indeed.com/applystart?jk=442ad7cc38...   
2     https://in.indeed.com/applystart?jk=e0fe53f38f...   
3     https://in.indeed.com/applystart?jk=363b96425a...   
4                                                   NaN   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499                                                NaN   
5500                                                NaN   
5501                                      

In [140]:
df.shape


(5502, 11)

In [141]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5502 entries, 0 to 5501
Data columns (total 11 columns):
id                   5502 non-null object
company              5408 non-null object
positionName         5502 non-null object
description          5502 non-null object
salary               1248 non-null object
location             5502 non-null object
rating               3128 non-null float64
reviewsCount         3128 non-null float64
postedAt             5502 non-null object
externalApplyLink    4044 non-null object
url                  5502 non-null object
dtypes: float64(2), object(9)
memory usage: 473.0+ KB


In [142]:
df['All'] = df[df.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)

In [143]:
df

id                                         company  \
0     2567a216d4af7021                                            AT&T   
1     442ad7cc38a6f7b8                           ICICI Prudential Life   
2     e0fe53f38f84e7bd                           ICICI Prudential Life   
3     363b96425a82d12d                                    TMI Group IN   
4     215ece39050fb3f5                   Shairu Gems Diamonds PVT.LTD.   
...                ...                                             ...   
5497  f53ad1277acdc74c                                   VISION ESTEEM   
5498  2b1b759b9c3a9246                                 L.R. Patel & Co   
5499  745a1ac63a001f46                Proactive Consultants & Services   
5500  d7901b874316b5d7  American Academy of Financial Management India   
5501  837f8b5ef252bcd0                          SV Placement Solutions   

                     positionName  \
0      SPECIALIST, DATA ANALYTICS   
1                  Data scientist   
2           Data scientist - Lead   
3                 Bot NLP Analyst   
4           Senior Data Scientist   
...                           ...   
5497           Executive HR Admin   
5498                 HR Recruiter   
5499                 HR Recruiter   
5500        Recruitment Executive   
5501  HR Recruiter (females only)   

                                            description  \
0     \n \n  Experienced data analyst position that ...   
1     Roles and responsibilities:\n 1. Data processi...   
2     Roles and responsibilities:\n 1. Data processi...   
3     \n Job Information \n \n \n  \n   \n    Salary...   
4     Sr. Data Analyst,\nShairu Gems Diamonds PVT. L...   
...                                                 ...   
5497  Urgently looking Executive HR and Admin for le...   
5498  JOB OVERVIEW: The HR Assistant duties involve ...   
5499  Dear candidates,\nWe have an urgent Opening fo...   
5500  Roles & Responsibilities :\nDesign and update ...   
5501  \n Partnering with hiring managers to determin...   

                              salary                location  rating  \
0                                NaN    Hyderabad, Telangana     3.7   
1                                NaN     Mumbai, Maharashtra     4.0   
2                                NaN     Mumbai, Maharashtra     4.0   
3     ₹10,00,000 - ₹16,00,000 a year    Hyderabad, Telangana     NaN   
4          ₹25,000 - ₹35,000 a month          Surat, Gujarat     NaN   
...                              ...                     ...     ...   
5497       ₹20,000 - ₹25,000 a month  Chandigarh, Chandigarh     NaN   
5498       ₹15,000 - ₹20,000 a month      Ahmedabad, Gujarat     NaN   
5499       ₹20,000 - ₹25,000 a month        New Delhi, Delhi     NaN   
5500       ₹20,000 - ₹25,000 a month            Delhi, Delhi     NaN   
5501        ₹8,000 - ₹12,000 a month         Patiala, Punjab     5.0   

      reviewsCount     postedAt  \
0          43942.0        Today   
1           1391.0  Just posted   
2           1391.0  Just posted   
3              NaN    1 day ago   
4              NaN        Today   
...            ...          ...   
5497           NaN   2 days ago   
5498           NaN   2 days ago   
5499           NaN   2 days ago   
5500           NaN   2 days ago   
5501           2.0   2 days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=2567a216d4...   
1     https://in.indeed.com/applystart?jk=442ad7cc38...   
2     https://in.indeed.com/applystart?jk=e0fe53f38f...   
3     https://in.indeed.com/applystart?jk=363b96425a...   
4                                                   NaN   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499                                                NaN   
5500                                                NaN   
5501                                      

In [144]:
df['All']

0       2567a216d4af7021,AT&T,SPECIALIST, DATA ANALYTI...
1       442ad7cc38a6f7b8,ICICI Prudential Life,Data sc...
2       e0fe53f38f84e7bd,ICICI Prudential Life,Data sc...
3       363b96425a82d12d,TMI Group IN,Bot NLP Analyst,...
4       215ece39050fb3f5,Shairu Gems Diamonds PVT.LTD....
                              ...                        
5497    f53ad1277acdc74c,VISION ESTEEM,Executive HR Ad...
5498    2b1b759b9c3a9246,L.R. Patel & Co,HR Recruiter,...
5499    745a1ac63a001f46,Proactive Consultants & Servi...
5500    d7901b874316b5d7,American Academy of Financial...
5501    837f8b5ef252bcd0,SV Placement Solutions,HR Rec...
Name: All, Length: 5502, dtype: object

In [145]:
df["description"].replace(r'\n','', regex=True,inplace=True)
df["description"].replace(r'\r','', regex=True,inplace=True)  
df = df.replace(' ', '')
df.description = df.description.str.strip()
df.All = df.All.str.strip()

In [146]:
df

id                                         company  \
0     2567a216d4af7021                                            AT&T   
1     442ad7cc38a6f7b8                           ICICI Prudential Life   
2     e0fe53f38f84e7bd                           ICICI Prudential Life   
3     363b96425a82d12d                                    TMI Group IN   
4     215ece39050fb3f5                   Shairu Gems Diamonds PVT.LTD.   
...                ...                                             ...   
5497  f53ad1277acdc74c                                   VISION ESTEEM   
5498  2b1b759b9c3a9246                                 L.R. Patel & Co   
5499  745a1ac63a001f46                Proactive Consultants & Services   
5500  d7901b874316b5d7  American Academy of Financial Management India   
5501  837f8b5ef252bcd0                          SV Placement Solutions   

                     positionName  \
0      SPECIALIST, DATA ANALYTICS   
1                  Data scientist   
2           Data scientist - Lead   
3                 Bot NLP Analyst   
4           Senior Data Scientist   
...                           ...   
5497           Executive HR Admin   
5498                 HR Recruiter   
5499                 HR Recruiter   
5500        Recruitment Executive   
5501  HR Recruiter (females only)   

                                            description  \
0     Experienced data analyst position that uses te...   
1     Roles and responsibilities: 1. Data processing...   
2     Roles and responsibilities: 1. Data processing...   
3     Job Information            Salary     ₹ 100000...   
4     Sr. Data Analyst,Shairu Gems Diamonds PVT. LTD...   
...                                                 ...   
5497  Urgently looking Executive HR and Admin for le...   
5498  JOB OVERVIEW: The HR Assistant duties involve ...   
5499  Dear candidates,We have an urgent Opening for ...   
5500  Roles & Responsibilities :Design and update jo...   
5501  Partnering with hiring managers to determine s...   

                              salary                location  rating  \
0                                NaN    Hyderabad, Telangana     3.7   
1                                NaN     Mumbai, Maharashtra     4.0   
2                                NaN     Mumbai, Maharashtra     4.0   
3     ₹10,00,000 - ₹16,00,000 a year    Hyderabad, Telangana     NaN   
4          ₹25,000 - ₹35,000 a month          Surat, Gujarat     NaN   
...                              ...                     ...     ...   
5497       ₹20,000 - ₹25,000 a month  Chandigarh, Chandigarh     NaN   
5498       ₹15,000 - ₹20,000 a month      Ahmedabad, Gujarat     NaN   
5499       ₹20,000 - ₹25,000 a month        New Delhi, Delhi     NaN   
5500       ₹20,000 - ₹25,000 a month            Delhi, Delhi     NaN   
5501        ₹8,000 - ₹12,000 a month         Patiala, Punjab     5.0   

      reviewsCount     postedAt  \
0          43942.0        Today   
1           1391.0  Just posted   
2           1391.0  Just posted   
3              NaN    1 day ago   
4              NaN        Today   
...            ...          ...   
5497           NaN   2 days ago   
5498           NaN   2 days ago   
5499           NaN   2 days ago   
5500           NaN   2 days ago   
5501           2.0   2 days ago   

                                      externalApplyLink  \
0     https://in.indeed.com/applystart?jk=2567a216d4...   
1     https://in.indeed.com/applystart?jk=442ad7cc38...   
2     https://in.indeed.com/applystart?jk=e0fe53f38f...   
3     https://in.indeed.com/applystart?jk=363b96425a...   
4                                                   NaN   
...                                                 ...   
5497                                                NaN   
5498                                                NaN   
5499                                                NaN   
5500                                                NaN   
5501                                      

# Put keywords of the CV into a dataframe

In [147]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

In [148]:
df2

title job highlights job description company overview industry  \
0     I              I               I                I        I   

                                                 All  
0  eld data ne-tuning pre-trained . transformer...

In [149]:
df.columns

Index(['id', 'company', 'positionName', 'description', 'salary', 'location',
       'rating', 'reviewsCount', 'postedAt', 'externalApplyLink', 'url',
       'All'],
      dtype='object')

# Recomendation Function

#klnsdsd

In [150]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['positionName', 'company',"location",'id','description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        
        recommendation.at[count, 'positionName'] = df['positionName'][i]
        recommendation.at[count, 'company'] = df['company'][i]
        recommendation.at[count, 'location'] = df['location'][i]
    
        recommendation.at[count, 'id'] = df.index[i]
        recommendation.at[count, 'description'] = df['description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

## cosine_similarity + TfidfVectorizer function

In [151]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])


In [152]:
len(output2)

5502

In [153]:
output2


[array([[0.0948479]]),
 array([[0.08444755]]),
 array([[0.08286146]]),
 array([[0.05021908]]),
 array([[0.02366749]]),
 array([[0.15034555]]),
 array([[0.14022676]]),
 array([[0.07491787]]),
 array([[0.0993632]]),
 array([[0.14995204]]),
 array([[0.1261072]]),
 array([[0.08431034]]),
 array([[0.10165101]]),
 array([[0.09643986]]),
 array([[0.00853993]]),
 array([[0.05932155]]),
 array([[0.0759698]]),
 array([[0.12229772]]),
 array([[0.06333626]]),
 array([[0.00534088]]),
 array([[0.0573566]]),
 array([[0.0707458]]),
 array([[0.03797819]]),
 array([[0.05862494]]),
 array([[0.05503736]]),
 array([[0.05776527]]),
 array([[0.12463742]]),
 array([[0.09500873]]),
 array([[0.14035184]]),
 array([[0.10671014]]),
 array([[0.02925474]]),
 array([[0.07469959]]),
 array([[0.08506797]]),
 array([[0.14452088]]),
 array([[0.08549496]]),
 array([[0.0236746]]),
 array([[0.07412399]]),
 array([[0.0093484]]),
 array([[0.04216777]]),
 array([[0.10975605]]),
 array([[0.0491647]]),
 array([[0.08877254]]),
 

In [154]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

positionName  \
0                      Machine Learning Lead Engineer   
1                                      Data Scientist   
2                      Data Science - Knowledge Graph   
3                         Manager MLOps, Data Science   
4                         Manager MLOps, Data Science   
..                                                ...   
95  Deputy Manager-Aftermarket and Service (Data S...   
96                          Data Science (NLP) Intern   
97                Data Science and Business Analytics   
98       Lead Machine Learning Firmware Test Engineer   
99       Lead Machine Learning Firmware Test Engineer   

                    company              location  \
0                    Wasoko  Bengaluru, Karnataka   
1   Chubb INA Holdings Inc.  Bengaluru, Karnataka   
2   Chubb INA Holdings Inc.  Bengaluru, Karnataka   
3    Mondelēz International   Mumbai, Maharashtra   
4    Mondelēz International   Mumbai, Maharashtra   
..                      ...                   ...   
95          Pratt & Whitney  Bengaluru, Karnataka   
96               Emplay Inc                Remote   
97            Zotto Limited          Delhi, Delhi   
98                   Axiado  Hyderabad, Telangana   
99                   Axiado  Hyderabad, Telangana   

                                          description     score  JobID  
0   Summary  We are looking for an experienced ML ...  0.227356  480.0  
1   Job Requirements  Responsibilities Work with b...  0.218374   91.0  
2   Work Experience Work with business partners gl...  0.216345   95.0  
3   Job Description   Are You Ready to Make It Hap...  0.208801  382.0  
4   Job Description   Are You Ready to Make It Hap...  0.208801  982.0  
..                                                ...       ...    ...  
95  Date Posted:  +91-XXXXXXXXXX:00  Country: Indi...   0.13687   66.0  
96  Job Title: NLP/Data Science InternStipend- 20,...  0.135837  430.0  
97  We are looking for a Data Scientist who will s...  0.135803  306.0  
98  Company Description  Axiado is an AI-enhanced ...  0.134965  338.0  
99  Company Description  Axiado is an AI-enhanced ...  0.134965  872.0  

[100 rows x 6 columns]

## cosine_similarity + CountVectorizer

In [155]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All']) #converting job data into vectors using count vectorizers
count_jobid

<5502x46684 sparse matrix of type '<class 'numpy.int64'>'
	with 1652794 stored elements in Compressed Sparse Row format>

In [156]:
# print(count_jobid)


In [157]:
user_count = count_vectorizer.transform(df2['All'])#converting user cv data into vectors using count vectorizers
user_count

<1x46684 sparse matrix of type '<class 'numpy.int64'>'
	with 153 stored elements in Compressed Sparse Row format>

In [158]:
print(user_count)


  (0, 2274)	2
  (0, 2325)	2
  (0, 2327)	2
  (0, 12586)	2
  (0, 12588)	2
  (0, 12913)	2
  (0, 13308)	5
  (0, 13530)	2
  (0, 13541)	3
  (0, 13564)	2
  (0, 13569)	2
  (0, 13633)	2
  (0, 13859)	2
  (0, 14410)	4
  (0, 14577)	2
  (0, 15198)	2
  (0, 15611)	4
  (0, 15905)	2
  (0, 19454)	2
  (0, 21367)	2
  (0, 21418)	3
  (0, 21648)	8
  (0, 21835)	2
  (0, 21915)	2
  (0, 22178)	2
  :	:
  (0, 42469)	4
  (0, 42728)	2
  (0, 43238)	2
  (0, 43274)	4
  (0, 43430)	2
  (0, 43508)	4
  (0, 43509)	2
  (0, 43860)	2
  (0, 43891)	1
  (0, 43920)	2
  (0, 43943)	2
  (0, 44067)	4
  (0, 44106)	2
  (0, 44186)	2
  (0, 44340)	2
  (0, 44775)	4
  (0, 44880)	2
  (0, 44898)	3
  (0, 44922)	2
  (0, 44924)	2
  (0, 45014)	2
  (0, 45919)	2
  (0, 46069)	4
  (0, 46139)	2
  (0, 46227)	2


In [159]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
#output3

In [160]:
output3

[array([[0.18863457]]),
 array([[0.2481385]]),
 array([[0.24711524]]),
 array([[0.12716114]]),
 array([[0.12430384]]),
 array([[0.23386668]]),
 array([[0.20115459]]),
 array([[0.20418955]]),
 array([[0.15770306]]),
 array([[0.23541296]]),
 array([[0.25080731]]),
 array([[0.18570727]]),
 array([[0.18231442]]),
 array([[0.22774789]]),
 array([[0.05537236]]),
 array([[0.0799583]]),
 array([[0.17849324]]),
 array([[0.30074646]]),
 array([[0.1170298]]),
 array([[0.05451707]]),
 array([[0.13573859]]),
 array([[0.15172833]]),
 array([[0.08835674]]),
 array([[0.17444216]]),
 array([[0.13318677]]),
 array([[0.22569545]]),
 array([[0.1761057]]),
 array([[0.18522631]]),
 array([[0.21356688]]),
 array([[0.16262122]]),
 array([[0.07621885]]),
 array([[0.17871404]]),
 array([[0.20447945]]),
 array([[0.26653906]]),
 array([[0.15601432]]),
 array([[0.09008666]]),
 array([[0.14537883]]),
 array([[0.07635354]]),
 array([[0.12838091]]),
 array([[0.21095305]]),
 array([[0.12037814]]),
 array([[0.20474689]

In [161]:
df.rating

0       3.7
1       4.0
2       4.0
3       NaN
4       NaN
       ... 
5497    NaN
5498    NaN
5499    NaN
5500    NaN
5501    5.0
Name: rating, Length: 5502, dtype: float64

In [162]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

positionName  \
0               Python Machine Learning Engineer   
1                      MACHINE LEARNING ENGINEER   
2                      MACHINE LEARNING ENGINEER   
3                  Data Scientist (India Remote)   
4                  Data Scientist (India Remote)   
..                                           ...   
95  Lead Machine Learning Firmware Test Engineer   
96                              Machine Learning   
97                     Machine Learning Engineer   
98                     Machine Learning Engineer   
99                                Data Scientist   

                         company              location  \
0         Vingsfire HRIM Pvt Ltd   Madurai, Tamil Nadu   
1            Amanzi Technologies  Noida, Uttar Pradesh   
2            Amanzi Technologies  Noida, Uttar Pradesh   
3                  Token Metrics  Bengaluru, Karnataka   
4                  Token Metrics  Bengaluru, Karnataka   
..                           ...                   ...   
95                        Axiado  Hyderabad, Telangana   
96     Think Future Technologies      Gurgaon, Haryana   
97                         Apple  Bengaluru, Karnataka   
98                         Apple  Bengaluru, Karnataka   
99  Ergode IT Services Pvt. ltd.   Mumbai, Maharashtra   

                                          description     score  JobID  
0   Role : Senior Python DeveloperExperience: 5+ Y...   0.36223  473.0  
1   Amanzi Technologies Pvt. Ltd.                 ...  0.357619  400.0  
2   Amanzi Technologies Pvt. Ltd.                 ...  0.357619  920.0  
3   Token Metrics is searching for a highly capabl...  0.356092   74.0  
4   Token Metrics is searching for a highly capabl...  0.356092  531.0  
..                                                ...       ...    ...  
95  Company Description  Axiado is an AI-enhanced ...  0.237696  872.0  
96  Exp: 2 + Years  Location: Gurgaon/ Remote  Ski...  0.237584  352.0  
97  Summary                Posted: Dec 7, 2022    ...  0.236778  225.0  
98  Summary                Posted: Dec 7, 2022    ...  0.236778  710.0  
99  Role Description - (Mumbai Based and Immediate...  0.236372  327.0  

[100 rows x 6 columns]

In [163]:
cv.description[1]

'Amanzi Technologies Pvt. Ltd.                              Permanent                              Noida                              Posted 3 weeks ago                          Out of the box solution          Responsibilities:      Designing and developing machine learning and deep learning systems.    Running machine learning tests and experiments.    Implementing appropriate ML algorithms.        Job brief:   We are looking for a Machine Learning (ML) Engineer to help us create artificial intelligence products.   Machine Learning Engineer responsibilities include creating machine learning models and retraining systems. To do this job successfully, you need exceptional skills in statistics and programming. If you also have knowledge of data science and software engineering, we’d like to meet you.   Your ultimate goal will be to shape and build efficient self-learning applications.   Responsibilities:      Study and transform data science prototypes.    Design machine learning system

## TfidfVectorizer + NearestNeighbors

In [164]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    
    KNN = NearestNeighbors(n_neighbors=100,p=2)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

positionName  \
0                                      Data Scientist   
1                      Data Science - Knowledge Graph   
2                         Manager MLOps, Data Science   
3                         Manager MLOps, Data Science   
4                           ASSOCIATE DEVOPS ENGINEER   
..                                                ...   
94  Deputy Manager-Aftermarket and Service (Data S...   
95                          Data Science (NLP) Intern   
96                Data Science and Business Analytics   
97       Lead Machine Learning Firmware Test Engineer   
98       Lead Machine Learning Firmware Test Engineer   

                    company              location  \
0   Chubb INA Holdings Inc.  Bengaluru, Karnataka   
1   Chubb INA Holdings Inc.  Bengaluru, Karnataka   
2    Mondelēz International   Mumbai, Maharashtra   
3    Mondelēz International   Mumbai, Maharashtra   
4           SKS Enterpprise   Chennai, Tamil Nadu   
..                      ...                   ...   
94          Pratt & Whitney  Bengaluru, Karnataka   
95               Emplay Inc                Remote   
96            Zotto Limited          Delhi, Delhi   
97                   Axiado  Hyderabad, Telangana   
98                   Axiado  Hyderabad, Telangana   

                                          description    score  JobID  
0   Job Requirements  Responsibilities Work with b...   1.2503   91.0  
1   Work Experience Work with business partners gl...  1.25192   95.0  
2   Job Description   Are You Ready to Make It Hap...  1.25793  982.0  
3   Job Description   Are You Ready to Make It Hap...  1.25793  382.0  
4   Position Name - Associate DevOps Engineer    L...  1.26768  779.0  
..                                                ...      ...    ...  
94  Date Posted:  +91-XXXXXXXXXX:00  Country: Indi...  1.31387   66.0  
95  Job Title: NLP/Data Science InternStipend- 20,...  1.31466  430.0  
96  We are looking for a Data Scientist who will s...  1.31468  306.0  
97  Company Description  Axiado is an AI-enhanced ...  1.31532  338.0  
98  Company Description  Axiado is an AI-enhanced ...  1.31532  872.0  

[99 rows x 6 columns]

In [165]:

knn.to_csv('knn.csv', index=False)

In [166]:
cv

positionName  \
0               Python Machine Learning Engineer   
1                      MACHINE LEARNING ENGINEER   
2                      MACHINE LEARNING ENGINEER   
3                  Data Scientist (India Remote)   
4                  Data Scientist (India Remote)   
..                                           ...   
95  Lead Machine Learning Firmware Test Engineer   
96                              Machine Learning   
97                     Machine Learning Engineer   
98                     Machine Learning Engineer   
99                                Data Scientist   

                         company              location  \
0         Vingsfire HRIM Pvt Ltd   Madurai, Tamil Nadu   
1            Amanzi Technologies  Noida, Uttar Pradesh   
2            Amanzi Technologies  Noida, Uttar Pradesh   
3                  Token Metrics  Bengaluru, Karnataka   
4                  Token Metrics  Bengaluru, Karnataka   
..                           ...                   ...   
95                        Axiado  Hyderabad, Telangana   
96     Think Future Technologies      Gurgaon, Haryana   
97                         Apple  Bengaluru, Karnataka   
98                         Apple  Bengaluru, Karnataka   
99  Ergode IT Services Pvt. ltd.   Mumbai, Maharashtra   

                                          description     score  JobID  
0   Role : Senior Python DeveloperExperience: 5+ Y...   0.36223  473.0  
1   Amanzi Technologies Pvt. Ltd.                 ...  0.357619  400.0  
2   Amanzi Technologies Pvt. Ltd.                 ...  0.357619  920.0  
3   Token Metrics is searching for a highly capabl...  0.356092   74.0  
4   Token Metrics is searching for a highly capabl...  0.356092  531.0  
..                                                ...       ...    ...  
95  Company Description  Axiado is an AI-enhanced ...  0.237696  872.0  
96  Exp: 2 + Years  Location: Gurgaon/ Remote  Ski...  0.237584  352.0  
97  Summary                Posted: Dec 7, 2022    ...  0.236778  225.0  
98  Summary                Posted: Dec 7, 2022    ...  0.236778  710.0  
99  Role Description - (Mumbai Based and Immediate...  0.236372  327.0  

[100 rows x 6 columns]

## Combined TFIDF, CV and KNN result together, to make a dataframe "final"


In [171]:
merge1 = knn[['JobID','positionName', 'score']].merge(TF[['JobID','score']], on= "JobID")

In [172]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()a

final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

JobID                    positionName      KNN    TF-IDF        CV
0   91.0                  Data Scientist   1.2503  0.218374  0.304615
1   95.0  Data Science - Knowledge Graph  1.25192  0.216345  0.302467
2  779.0       ASSOCIATE DEVOPS ENGINEER  1.26768  0.196495  0.281634
3  400.0       MACHINE LEARNING ENGINEER  1.27042  0.193014  0.357619
4  920.0       MACHINE LEARNING ENGINEER   1.2705  0.192913  0.357619

In [173]:
final

JobID                                       positionName      KNN  \
0     91.0                                     Data Scientist   1.2503   
1     95.0                     Data Science - Knowledge Graph  1.25192   
2    779.0                          ASSOCIATE DEVOPS ENGINEER  1.26768   
3    400.0                          MACHINE LEARNING ENGINEER  1.27042   
4    920.0                          MACHINE LEARNING ENGINEER   1.2705   
5     54.0                          Machine Learning Engineer  1.27331   
6    562.0                          Machine Learning Engineer  1.27331   
7    183.0                              Senior Data Scientist   1.2775   
8    334.0                                     Data Scientist  1.28278   
9    337.0                                     Data Scientist  1.28318   
10   845.0                                         AVP-DEVOPS  1.28735   
11   473.0                   Python Machine Learning Engineer  1.28815   
12    74.0                      Data Scientist (India Remote)  1.28919   
13   531.0                      Data Scientist (India Remote)  1.28919   
14   164.0                        Python Data Science Trainer  1.29025   
15   721.0                                Automation Engineer  1.29304   
16   711.0                          Machine Learning Engineer  1.29328   
17   236.0                          Machine Learning Engineer  1.29334   
18   541.0                    AI Engineer_MLOPS_3 to 10 years  1.29397   
19  3711.0                    AI Engineer_MLOPS_3 to 10 years  1.29397   
20   307.0          Data Science - Lead & Manager/Sr. Manager  1.29573   
21   221.0                          Machine Learning Engineer  1.29857   
22   713.0                          Machine Learning Engineer  1.29862   
23   285.0                                       AI Tech Lead  1.29941   
24   275.0                 Senior Machine Learning Researcher  1.29981   
25   752.0                          Machine Learning Engineer   1.3005   
26  1859.0                          Machine Learning Engineer  1.30058   
27   229.0                          Machine Learning Engineer  1.30065   
28   444.0                              Data Science Engineer  1.30085   
29   463.0                          Machine Learning Engineer  1.30232   
30   140.0                                     Data Scientist    1.303   
31   225.0                          Machine Learning Engineer   1.3037   
32   710.0                          Machine Learning Engineer   1.3037   
33   284.0                   Senior Machine Learning Engineer  1.30428   
34  1970.0                   Senior Machine Learning Engineer  1.30449   
35   740.0                   Senior Machine Learning Engineer  1.30449   
36   327.0                                     Data Scientist  1.30494   
37   450.0                                 Sr. Data Scientist  1.30596   
38   305.0                                     Data Scientist  1.30698   
39   741.0      SatSure Analytics - Machine Learning Engineer  1.30735   
40   296.0      SatSure Analytics - Machine Learning Engineer  1.30735   
41  1999.0      SatSure Analytics - Machine Learning Engineer  1.30735   
42   294.0  Senior Machine Learning Engineer Opportunity A...  1.30772   
43   738.0  Senior Machine Learning Engineer Opportunity A...  1.30776   
44   547.0                              Data Science Engineer  1.30804   
45    33.0                              Data Science Engineer  1.30804   
46   199.0                          Machine Learning Engineer  1.30986   
47   714.0                          Machine Learning Engineer  1.30986   
48    78.0                         Machine Learning Developer  1.31031   
49   464.0                            Machine Learning Intern  1.31086   
50   871.0              Machine Learning Engineer (2-4 years)  1.31352   
51   315.0              Machine Learning Engineer (2-4 years)  1.31352   
52   373.0                                     AI/ML Engineer  1.31368   
53   917.

In [174]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                                       positionName       KNN  \
0     91.0                                     Data Scientist  0.333333   
1     95.0                     Data Science - Knowledge Graph  0.325020   
3    400.0                          MACHINE LEARNING ENGINEER  0.230180   
4    920.0                          MACHINE LEARNING ENGINEER  0.229775   
11   473.0                   Python Machine Learning Engineer  0.139292   
2    779.0                          ASSOCIATE DEVOPS ENGINEER  0.244245   
13   531.0                      Data Scientist (India Remote)  0.133951   
12    74.0                      Data Scientist (India Remote)  0.133951   
8    334.0                                     Data Scientist  0.166818   
9    337.0                                     Data Scientist  0.164773   
6    562.0                          Machine Learning Engineer  0.215372   
5     54.0                          Machine Learning Engineer  0.215372   
7    183.0                              Senior Data Scientist  0.193869   
15   721.0                                Automation Engineer  0.114221   
20   307.0          Data Science - Lead & Manager/Sr. Manager  0.100447   
10   845.0                                         AVP-DEVOPS  0.143409   
14   164.0                        Python Data Science Trainer  0.128530   
24   275.0                 Senior Machine Learning Researcher  0.079496   
37   450.0                                 Sr. Data Scientist  0.048011   
25   752.0                          Machine Learning Engineer  0.075967   
26  1859.0                          Machine Learning Engineer  0.075563   
27   229.0                          Machine Learning Engineer  0.075225   
19  3711.0                    AI Engineer_MLOPS_3 to 10 years  0.109478   
18   541.0                    AI Engineer_MLOPS_3 to 10 years  0.109478   
49   464.0                            Machine Learning Intern  0.022859   
23   285.0                                       AI Tech Lead  0.081553   
30   140.0                                     Data Scientist  0.063170   
16   711.0                          Machine Learning Engineer  0.112980   
17   236.0                          Machine Learning Engineer  0.112710   
33   284.0                   Senior Machine Learning Engineer  0.056607   
34  1970.0                   Senior Machine Learning Engineer  0.055522   
35   740.0                   Senior Machine Learning Engineer  0.055522   
21   221.0                          Machine Learning Engineer  0.085897   
22   713.0                          Machine Learning Engineer  0.085637   
41  1999.0      SatSure Analytics - Machine Learning Engineer  0.040846   
40   296.0      SatSure Analytics - Machine Learning Engineer  0.040846   
39   741.0      SatSure Analytics - Machine Learning Engineer  0.040846   
29   463.0                          Machine Learning Engineer  0.066629   
28   444.0                              Data Science Engineer  0.074172   
38   305.0                                     Data Scientist  0.042749   
44   547.0                              Data Science Engineer  0.037347   
45    33.0                              Data Science Engineer  0.037347   
42   294.0  Senior Machine Learning Engineer Opportunity A...  0.038943   
43   738.0  Senior Machine Learning Engineer Opportunity A...  0.038766   
50   871.0              Machine Learning Engineer (2-4 years)  0.009240   
51   315.0              Machine Learning Engineer (2-4 years)  0.009240   
31   225.0                          Machine Learning Engineer  0.059579   
32   710.0                          Machine Learning Engineer  0.059574   
36   327.0                                     Data Scientist  0.053206   
48    78.0                         Machine Learning Developer  0.025696   
47   714.0                          Machine Learning Engineer  0.027998   
46   199.0                          Machine Learning Engineer  0.027998   
52   373.0                    

In [176]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

JobID                                       positionName       KNN  \
0     91.0                                     Data Scientist  0.333333   
1     95.0                     Data Science - Knowledge Graph  0.325020   
3    400.0                          MACHINE LEARNING ENGINEER  0.230180   
4    920.0                          MACHINE LEARNING ENGINEER  0.229775   
11   473.0                   Python Machine Learning Engineer  0.139292   
2    779.0                          ASSOCIATE DEVOPS ENGINEER  0.244245   
13   531.0                      Data Scientist (India Remote)  0.133951   
12    74.0                      Data Scientist (India Remote)  0.133951   
8    334.0                                     Data Scientist  0.166818   
9    337.0                                     Data Scientist  0.164773   
6    562.0                          Machine Learning Engineer  0.215372   
5     54.0                          Machine Learning Engineer  0.215372   
7    183.0                              Senior Data Scientist  0.193869   
15   721.0                                Automation Engineer  0.114221   
20   307.0          Data Science - Lead & Manager/Sr. Manager  0.100447   
10   845.0                                         AVP-DEVOPS  0.143409   
14   164.0                        Python Data Science Trainer  0.128530   
24   275.0                 Senior Machine Learning Researcher  0.079496   
37   450.0                                 Sr. Data Scientist  0.048011   
25   752.0                          Machine Learning Engineer  0.075967   
26  1859.0                          Machine Learning Engineer  0.075563   
27   229.0                          Machine Learning Engineer  0.075225   
19  3711.0                    AI Engineer_MLOPS_3 to 10 years  0.109478   
18   541.0                    AI Engineer_MLOPS_3 to 10 years  0.109478   
49   464.0                            Machine Learning Intern  0.022859   
23   285.0                                       AI Tech Lead  0.081553   
30   140.0                                     Data Scientist  0.063170   
16   711.0                          Machine Learning Engineer  0.112980   
17   236.0                          Machine Learning Engineer  0.112710   
33   284.0                   Senior Machine Learning Engineer  0.056607   
34  1970.0                   Senior Machine Learning Engineer  0.055522   
35   740.0                   Senior Machine Learning Engineer  0.055522   
21   221.0                          Machine Learning Engineer  0.085897   
22   713.0                          Machine Learning Engineer  0.085637   
41  1999.0      SatSure Analytics - Machine Learning Engineer  0.040846   
40   296.0      SatSure Analytics - Machine Learning Engineer  0.040846   
39   741.0      SatSure Analytics - Machine Learning Engineer  0.040846   
29   463.0                          Machine Learning Engineer  0.066629   
28   444.0                              Data Science Engineer  0.074172   
38   305.0                                     Data Scientist  0.042749   
44   547.0                              Data Science Engineer  0.037347   
45    33.0                              Data Science Engineer  0.037347   
42   294.0  Senior Machine Learning Engineer Opportunity A...  0.038943   
43   738.0  Senior Machine Learning Engineer Opportunity A...  0.038766   
50   871.0              Machine Learning Engineer (2-4 years)  0.009240   
51   315.0              Machine Learning Engineer (2-4 years)  0.009240   
31   225.0                          Machine Learning Engineer  0.059579   
32   710.0                          Machine Learning Engineer  0.059574   
36   327.0                                     Data Scientist  0.053206   
48    78.0                         Machine Learning Developer  0.025696   
47   714.0                          Machine Learning Engineer  0.027998   
46   199.0                          Machine Learning Engineer  0.027998   
52   373.0                    

In [179]:
# final2.merge(df, on="JobID")
final_df = df.merge(final2, on="id")
final_df

KeyError: 'id'